OpenHRC: HybridFeedbackController Class Reference
HybridFeedbackController Class Reference
#include <hybrid_feedback_controller.hpp>
Public Member Functions
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
virtual void initInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Private Member Functions
VectorXd PIControl (const KDL::Frame &frame, const KDL::Frame &pose, const KDL::Twist &twist)
VectorXd PIControl (const VectorXd &e, const KDL::Twist &twist)
VectorXd adaptivePIControl (const rclcpp::Time t, const KDL::Frame &frame, const KDL::Frame &pose, const KDL::Twist &twist)
VectorXd adaptivePIControl (const rclcpp::Time t, const VectorXd &e, const KDL::Twist &twist)
VectorXd forceFeedbackControl (const KDL::Frame &frame, const KDL::Frame &pose, const VectorXd f)
VectorXd forceFeedbackControl (const VectorXd &e, const VectorXd f)
Private Attributes
VectorXd x
VectorXd xd
std::vector< double > t0_f
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Detailed Description
Definition at line 6 of file hybrid_feedback_controller.hpp.
Member Function Documentation
adaptivePIControl() [1/2]
VectorXd HybridFeedbackController::adaptivePIControl (const rclcpp::Time t, const KDL::Frame & frame, const KDL::Frame & pose, const KDL::Twist & twist) private
Definition at line 56 of file hybrid_feedback_controller.cpp.
References pseudoSigmoid(), and t0_f.
Referenced by updateTargetPose().
adaptivePIControl() [2/2]
VectorXd HybridFeedbackController::adaptivePIControl (const rclcpp::Time t, const VectorXd & e, const KDL::Twist & twist) private
Definition at line 74 of file hybrid_feedback_controller.cpp.
References Interface::e, pseudoSigmoid(), and t0_f.
forceFeedbackControl() [1/2]
VectorXd HybridFeedbackController::forceFeedbackControl (const KDL::Frame & frame, const KDL::Frame & pose, const VectorXd f) private
Definition at line 125 of file hybrid_feedback_controller.cpp.
Referenced by updateTargetPose().
forceFeedbackControl() [2/2]
VectorXd HybridFeedbackController::forceFeedbackControl (const VectorXd & e, const VectorXd f) private
Definition at line 134 of file hybrid_feedback_controller.cpp.
References Interface::e.
initInterface()
void HybridFeedbackController::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file hybrid_feedback_controller.cpp.
References t0_f.
Interface() [1/2]
Interface::Interface (const std::shared_ptr< CartController > & controller) inline
Definition at line 57 of file interface.hpp.
Interface() [2/2]
Interface::Interface (const std::shared_ptr< CartController > & controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode) inline
Definition at line 60 of file interface.hpp.
PIControl() [1/2]
VectorXd HybridFeedbackController::PIControl (const KDL::Frame & frame, const KDL::Frame & pose, const KDL::Twist & twist) private
Definition at line 92 of file hybrid_feedback_controller.cpp.
Referenced by updateTargetPose().
PIControl() [2/2]
VectorXd HybridFeedbackController::PIControl (const VectorXd & e, const KDL::Twist & twist) private
Definition at line 109 of file hybrid_feedback_controller.cpp.
References Interface::e.
updateTargetPose()
void HybridFeedbackController::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 7 of file hybrid_feedback_controller.cpp.
References adaptivePIControl(), Interface::controller, Interface::e, forceFeedbackControl(), MyIK::getCartError(), PIControl(), and t0_f.
Member Data Documentation
t0_f
std::vector<double> HybridFeedbackController::t0_f private
Definition at line 16 of file hybrid_feedback_controller.hpp.
Referenced by adaptivePIControl(), initInterface(), and updateTargetPose().
x
VectorXd HybridFeedbackController::x private
Definition at line 7 of file hybrid_feedback_controller.hpp.
xd
VectorXd HybridFeedbackController::xd private
Definition at line 7 of file hybrid_feedback_controller.hpp.
The documentation for this class was generated from the following files:
hybrid_feedback_controller.hpp
hybrid_feedback_controller.cpp