OpenHRC: nav_msgs_utility::Odometry Class Reference
nav_msgs_utility::Odometry Class Reference
#include <Odometry.h>
Public Member Functions
void toVector_3dof (nav_msgs::msg::Odometry odom, Eigen::MatrixXd &vector)
void toVector_6dof (nav_msgs::msg::Odometry odom, Eigen::MatrixXd &vector)
void fromVector_3dof (Eigen::MatrixXd vector, nav_msgs::msg::Odometry &odom)
void fromVector_6dof (Eigen::MatrixXd vector, nav_msgs::msg::Odometry &odom)
void transFromOdom (nav_msgs::msg::Odometry odom, geometry_msgs::TransformStamped &trans_base_odom)
void transToOdom (nav_msgs::msg::Odometry odom, geometry_msgs::TransformStamped &trans_odom_base)
Detailed Description
Definition at line 15 of file Odometry.h.
Member Function Documentation
fromVector_3dof()
void nav_msgs_utility::Odometry::fromVector_3dof (Eigen::MatrixXd vector, nav_msgs::msg::Odometry & odom) inline
Definition at line 39 of file Odometry.h.
References tf2::toMsg().
fromVector_6dof()
void nav_msgs_utility::Odometry::fromVector_6dof (Eigen::MatrixXd vector, nav_msgs::msg::Odometry & odom) inline
Definition at line 48 of file Odometry.h.
References tf2::toMsg().
toVector_3dof()
void nav_msgs_utility::Odometry::toVector_3dof (nav_msgs::msg::Odometry odom, Eigen::MatrixXd & vector) inline
Definition at line 17 of file Odometry.h.
toVector_6dof()
void nav_msgs_utility::Odometry::toVector_6dof (nav_msgs::msg::Odometry odom, Eigen::MatrixXd & vector) inline
Definition at line 26 of file Odometry.h.
transFromOdom()
void nav_msgs_utility::Odometry::transFromOdom (nav_msgs::msg::Odometry odom, geometry_msgs::TransformStamped & trans_base_odom) inline
Definition at line 62 of file Odometry.h.
References tf2::fromMsg().
transToOdom()
void nav_msgs_utility::Odometry::transToOdom (nav_msgs::msg::Odometry odom, geometry_msgs::TransformStamped & trans_odom_base) inline
Definition at line 68 of file Odometry.h.
References tf2::fromMsg().
The documentation for this class was generated from the following file:
Odometry.h