OpenHRC: MarkerInterface Class Reference
MarkerInterface Class Reference
#include <marker_interface.hpp>
Public Member Functions
MarkerInterface (const std::shared_ptr< CartController > &controller)
~MarkerInterface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
virtual void initInterface () override
virtual void resetInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Private Member Functions
void configMarker ()
void processFeedback (const visualization_msgs::msg::InteractiveMarkerFeedback::ConstSharedPtr &feedback, rclcpp::Logger logger)
void markerThread ()
Private Attributes
visualization_msgs::msg::InteractiveMarker int_marker
std::unique_ptr< interactive_markers::InteractiveMarkerServer > server
KDL::Frame prevPoses
geometry_msgs::msg::Pose _markerPose
double _markerDt
rclcpp::Time t_prev
bool subFirst = false
bool _flagSubInteractiveMarker = false
int count_disable = 0
int updateCount = 0
visualization_msgs::msg::InteractiveMarkerFeedback _feedback
std::thread th
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Detailed Description
Definition at line 11 of file marker_interface.hpp.
Constructor & Destructor Documentation
MarkerInterface()
MarkerInterface::MarkerInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 36 of file marker_interface.hpp.
~MarkerInterface()
MarkerInterface::~MarkerInterface () inline
Definition at line 39 of file marker_interface.hpp.
References th.
Member Function Documentation
configMarker()
void MarkerInterface::configMarker () private
Definition at line 14 of file marker_interface.cpp.
References Interface::controller, int_marker, Interface::node, processFeedback(), Interface::robot_ns, server, and tf2::toMsg().
Referenced by initInterface().
initInterface()
void MarkerInterface::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file marker_interface.cpp.
References _markerPose, configMarker(), Interface::controller, markerThread(), th, and tf2::toMsg().
Interface() [1/2]
Interface::Interface (const std::shared_ptr< CartController > & controller) inline
Definition at line 57 of file interface.hpp.
Interface() [2/2]
Interface::Interface (const std::shared_ptr< CartController > & controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode) inline
Definition at line 60 of file interface.hpp.
markerThread()
void MarkerInterface::markerThread () private
Definition at line 73 of file marker_interface.cpp.
References _feedback, _flagSubInteractiveMarker, _markerPose, Interface::controller, count_disable, int_marker, Interface::interfaceRunning, Interface::mtx, server, subFirst, tf2::toMsg(), and Interface::updateIsEnable().
Referenced by initInterface().
processFeedback()
void MarkerInterface::processFeedback (const visualization_msgs::msg::InteractiveMarkerFeedback::ConstSharedPtr & feedback, rclcpp::Logger logger) private
Definition at line 67 of file marker_interface.cpp.
References _feedback, Interface::feedback(), Interface::mtx, and subFirst.
Referenced by configMarker().
resetInterface()
void MarkerInterface::resetInterface () override virtual
Reimplemented from Interface.
Definition at line 110 of file marker_interface.cpp.
References Interface::controller, int_marker, server, subFirst, and tf2::toMsg().
updateTargetPose()
void MarkerInterface::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 95 of file marker_interface.cpp.
References _flagSubInteractiveMarker, _markerPose, tf2::fromMsg(), and Interface::mtx.
Member Data Documentation
_feedback
visualization_msgs::msg::InteractiveMarkerFeedback MarkerInterface::_feedback private
Definition at line 30 of file marker_interface.hpp.
Referenced by markerThread(), and processFeedback().
_flagSubInteractiveMarker
bool MarkerInterface::_flagSubInteractiveMarker = false private
Definition at line 26 of file marker_interface.hpp.
Referenced by markerThread(), and updateTargetPose().
_markerDt
double MarkerInterface::_markerDt private
Definition at line 21 of file marker_interface.hpp.
_markerPose
geometry_msgs::msg::Pose MarkerInterface::_markerPose private
Definition at line 20 of file marker_interface.hpp.
Referenced by initInterface(), markerThread(), and updateTargetPose().
count_disable
int MarkerInterface::count_disable = 0 private
Definition at line 27 of file marker_interface.hpp.
Referenced by markerThread().
int_marker
visualization_msgs::msg::InteractiveMarker MarkerInterface::int_marker private
Definition at line 12 of file marker_interface.hpp.
Referenced by configMarker(), markerThread(), and resetInterface().
prevPoses
KDL::Frame MarkerInterface::prevPoses private
Definition at line 19 of file marker_interface.hpp.
server
std::unique_ptr<interactive_markers::InteractiveMarkerServer> MarkerInterface::server private
Definition at line 14 of file marker_interface.hpp.
Referenced by configMarker(), markerThread(), and resetInterface().
subFirst
bool MarkerInterface::subFirst = false private
Definition at line 24 of file marker_interface.hpp.
Referenced by markerThread(), processFeedback(), and resetInterface().
t_prev
rclcpp::Time MarkerInterface::t_prev private
Definition at line 22 of file marker_interface.hpp.
th
std::thread MarkerInterface::th private
Definition at line 31 of file marker_interface.hpp.
Referenced by initInterface(), and ~MarkerInterface().
updateCount
int MarkerInterface::updateCount = 0 private
Definition at line 28 of file marker_interface.hpp.
The documentation for this class was generated from the following files:
marker_interface.hpp
marker_interface.cpp