OpenHRC: TransformUtility Class Reference
TransformUtility Class Reference
#include <transform_utility.h>
Public Member Functions
TransformUtility (rclcpp::Node::SharedPtr node)
Affine3d getTransform (const std::string &target, const std::string &source, const rclcpp::Time &time, rclcpp::Duration timeout)
bool canTransform (const std::string &target, const std::string &source, const rclcpp::Time &time, rclcpp::Duration timeout)
Static Public Member Functions
static MatrixXd transformVel (VectorXd vel, const Affine3d trans)
static MatrixXd transformFT (VectorXd ft_in, const Affine3d trans)
static void transformFT (Vector3d force_in, Vector3d torque_in, const Affine3d trans, Vector3d &force_out, Vector3d &torque_out)
Protected Attributes
rclcpp::Node::SharedPtr node
std::shared_ptr< tf2_ros::TransformListener > tfListener { nullptr }
std::unique_ptr< tf2_ros::Buffer > tfBuffer
Affine3d Thandle_fp
Affine3d Thandle_ft
Affine3d Thandle_lidar
Affine3d T_l_fp
Affine3d T_h_fp
Affine3d T_c_fp
Affine3d T_color_depth
Detailed Description
Definition at line 19 of file transform_utility.h.
Constructor & Destructor Documentation
TransformUtility()
TransformUtility::TransformUtility (rclcpp::Node::SharedPtr node) inline
Definition at line 29 of file transform_utility.h.
References node, tfBuffer, and tfListener.
Member Function Documentation
canTransform()
bool TransformUtility::canTransform (const std::string & target, const std::string & source, const rclcpp::Time & time, rclcpp::Duration timeout) inline
Definition at line 73 of file transform_utility.h.
References tfBuffer.
getTransform()
Affine3d TransformUtility::getTransform (const std::string & target, const std::string & source, const rclcpp::Time & time, rclcpp::Duration timeout) inline
Definition at line 68 of file transform_utility.h.
References tfBuffer.
transformFT() [1/2]
static void TransformUtility::transformFT (Vector3d force_in, Vector3d torque_in, const Affine3d trans, Vector3d & force_out, Vector3d & torque_out) inline static
Definition at line 62 of file transform_utility.h.
transformFT() [2/2]
static MatrixXd TransformUtility::transformFT (VectorXd ft_in, const Affine3d trans) inline static
Definition at line 50 of file transform_utility.h.
References transformFT().
Referenced by geometry_msgs_utility::transformFT(), and transformFT().
transformVel()
static MatrixXd TransformUtility::transformVel (VectorXd vel, const Affine3d trans) inline static
Definition at line 35 of file transform_utility.h.
Member Data Documentation
node
rclcpp::Node::SharedPtr TransformUtility::node protected
Definition at line 23 of file transform_utility.h.
Referenced by TransformUtility().
T_c_fp
Affine3d TransformUtility::T_c_fp protected
Definition at line 26 of file transform_utility.h.
T_color_depth
Affine3d TransformUtility::T_color_depth protected
Definition at line 26 of file transform_utility.h.
T_h_fp
Affine3d TransformUtility::T_h_fp protected
Definition at line 26 of file transform_utility.h.
T_l_fp
Affine3d TransformUtility::T_l_fp protected
Definition at line 26 of file transform_utility.h.
tfBuffer
std::unique_ptr<tf2_ros::Buffer> TransformUtility::tfBuffer protected
Definition at line 25 of file transform_utility.h.
Referenced by canTransform(), getTransform(), and TransformUtility().
tfListener
std::shared_ptr<tf2_ros::TransformListener> TransformUtility::tfListener { nullptr } protected
Definition at line 24 of file transform_utility.h.
Referenced by TransformUtility().
Thandle_fp
Affine3d TransformUtility::Thandle_fp protected
Definition at line 26 of file transform_utility.h.
Thandle_ft
Affine3d TransformUtility::Thandle_ft protected
Definition at line 26 of file transform_utility.h.
Thandle_lidar
Affine3d TransformUtility::Thandle_lidar protected
Definition at line 26 of file transform_utility.h.
The documentation for this class was generated from the following file:
transform_utility.h