OpenHRC: CartController Class Reference
CartController Class Reference
#include <cart_controller.hpp>
Classes
struct s_cbJntState
struct s_initCmd
struct s_moveInitPos
Public Member Functions
CartController (rclcpp::Node::SharedPtr &node, const std::string robot, const std::string root_frame, const ControllerType controller, const double freq, const bool unique_state=false)
CartController (rclcpp::Node::SharedPtr &node, const std::string robot, const std::string root_frame, const int index, const ControllerType controller, const double freq, const bool unique_state=false)
CartController (rclcpp::Node::SharedPtr &node, const std::string robot, const std::string hw_config, const std::string root_frame, const int index, const ControllerType controller, const double freq, const bool unique_state=false)
int control ()
void sendIntJntCmd ()
void sendIntJntCmd (CartController::s_initCmd initCmd)
void sendIntJntCmd (VectorXd q_des_t, VectorXd dq_des_t, KDL::JntArray q_cur, bool lastLoop, double T, double s)
void update ()
Updates controller, i.e. computes the odometry and sets the new velocity commands.
void update (const rclcpp::Time &time, const rclcpp::Duration &period)
void starting (const rclcpp::Time &time)
Starts controller.
void stopping (const rclcpp::Time &time)
Stops controller.
void initFt ()
void getIKInput (double dt, KDL::JntArray &q_cur, KDL::Frame &des_eef_pose, KDL::Twist &des_eef_vel)
void getVelocity (const KDL::Frame &frame, const KDL::Frame &prev_frame, const double &dt, KDL::Twist &twist) const
void updateCurState ()
void getState (KDL::JntArray &q_cur, KDL::JntArray &dq_cur)
void getState (KDL::JntArray &q_cur, KDL::JntArray &dq_cur, KDL::Frame &frame, KDL::Twist &twist)
void getCartState (KDL::Frame &frame, KDL::Twist &twist)
void publishStates ()
void publishDesEffPoseVel (const KDL::Frame &des_eef_pose, const KDL::Twist &des_eef_vel)
void publishCurEffPoseVel (const KDL::Frame &cur_eef_pose, const KDL::Twist &cur_eef_vel)
void getDesState (const KDL::Frame &cur_pose, const KDL::Twist &cur_vel, KDL::Frame &des_pose, KDL::Twist &des_vel)
void publishState (const KDL::Frame &pose, const KDL::Twist &vel, rclcpp::Publisher< ohrc_msgs::msg::State >::SharedPtr publisher)
void publishState (const KDL::Frame &pose, const KDL::Twist &vel, const geometry_msgs::msg::Wrench &wrench, rclcpp::Publisher< ohrc_msgs::msg::State >::SharedPtr publisher)
void publishMarker (const KDL::JntArray q_cur)
void sendGripperCmd ()
void filterJnt (KDL::JntArray &q)
void updatePosFilterCutoff (const double posFreq)
void updateVelFilterCutoff (const double velFreq)
void updateJntFilterCutoff (const double jntFreq)
void updateFilterCutoff (const double velFreq, const double jntFreq)
void startOperation ()
void enableOperation ()
void disableOperation ()
bool getOperationEnable () const
void getInfo (std::string &chain_start, std::string &chain_end, Affine3d &T_base_root, std::shared_ptr< MyIK::MyIK > &myik)
std::string getChainStart () const
std::string getChainEnd () const
void JntToCart (const KDL::JntArray &q_in, KDL::Frame &p_out)
void JntToCart (const KDL::JntArray &q_in, const KDL::JntArray &dq_in, KDL::Frame &p_out, KDL::Twist &v_out)
void JntVelToCartVel (const KDL::JntArray &q_in, const KDL::JntArray &dq_in, KDL::Twist &v_out)
std::string getRobotNs () const
int getIndex ()
Affine3d getTransform_base (std::string target)
Affine3d getT_init () const
Affine3d getT_cur ()
Affine3d getT_root ()
Affine3d getT_base_world ()
geometry_msgs::msg::WrenchStamped getForceEef ()
VectorXd getForceEefVec ()
unsigned int getNJnt ()
std::vector< std::string > getNameJnt ()
bool isInitialized ()
void setDesired (const KDL::Frame &des_eef_pose, const KDL::Twist &des_eef_vel)
void getDesired (KDL::Frame &des_eef_pose, KDL::Twist &des_eef_vel)
void enablePoseFeedback ()
void disablePoseFeedback ()
Affine3d getTft_eff ()
KDL::JntArray getqRest ()
void setqRest (const KDL::JntArray &q_rest)
bool getFtFound ()
rclcpp::Node::SharedPtr getNode ()
void getInitCmd (VectorXd &q_des_t, VectorXd &dq_des_t, KDL::JntArray &q_cur, int &lastLoop, double &T, double &s)
void resetPose ()
void resetFt ()
void sendPosCmd (const KDL::JntArray &q_des, const KDL::JntArray &dq_des, const double &dt)
void sendVelCmd (const KDL::JntArray &q_des, const KDL::JntArray &dq_des, const double &dt)
bool getReseted ()
void setReseted (bool reseted)
Public Attributes
float gripperCmd = 1.0
rclcpp::SubscriptionOptions options
double dt
double freq = 500.0
const double eps = 1e-6
rclcpp::Publisher< std_msgs::msg::Float64MultiArray >::SharedPtr jntCmdPublisher
rclcpp::Publisher< std_msgs::msg::Float64 >::SharedPtr gripperCmdPublisher
rclcpp::Publisher< sensor_msgs::msg::JointState >::SharedPtr jntStateCmdPublisher
rclcpp::Publisher< trajectory_msgs::msg::JointTrajectory >::SharedPtr jntTrjCmdPublisher
rclcpp::Publisher< ohrc_msgs::msg::State >::SharedPtr desStatePublisher
rclcpp::Publisher< ohrc_msgs::msg::State >::SharedPtr curStatePublisher
std::mutex mtx
bool flagJntState = false
Protected Member Functions
void initMembers ()
void cbJntState (const sensor_msgs::msg::JointState::SharedPtr msg)
void cbForce (const geometry_msgs::msg::WrenchStamped::SharedPtr msg)
void initDesWithJnt (const KDL::JntArray &q_init)
virtual void initWithJnt (const KDL::JntArray &q_init)
void filterDesEffPoseVel (KDL::Frame &des_eef_pose, KDL::Twist &des_eef_vel)
int moveInitPos (const KDL::JntArray &q_cur, const KDL::JntArray &dq_cur, const std::vector< std::string > nameJnt, std::vector< int > idxSegJnt)
void sendPositionCmd (const VectorXd &q_des)
void sendJointStateCmd (const VectorXd &q_des, const VectorXd &dq_des)
void sendVelocityCmd (const VectorXd &dq_des)
void sendVelocityCmd (const VectorXd &q_des, const VectorXd &dq_des, const KDL::JntArray &q_cur, const bool &lastLoop)
void sendTrajectoryCmd (const VectorXd &q_des, const double &T)
void sendTrajectoryCmd (const VectorXd &q_des, const VectorXd &dq_des, const double &T)
void sendTrajectoryActionCmd (const VectorXd &q_des, const double &T)
void sendTrajectoryActionCmd (const VectorXd &q_des, const VectorXd &dq_des, const double &T)
void getTrajectoryCmd (const VectorXd &q_des, const double &T, trajectory_msgs::msg::JointTrajectory &cmd_trj)
void getTrajectoryCmd (const VectorXd &q_des, const VectorXd &dq_des, const double &T, trajectory_msgs::msg::JointTrajectory &cmd_trj)
Protected Attributes
SolverType solver
ControllerType controller
PublisherType publisher
rclcpp::Subscription< sensor_msgs::msg::JointState >::SharedPtr subJntState
rclcpp::Subscription< geometry_msgs::msg::WrenchStamped >::SharedPtr subForce
std::vector< bool * > subFlagPtrs
bool flagEffPose = false
Matrix3d _userManipU = Matrix3d::Identity()
bool flagArmMarker = false
bool useManipOpt = false
int num_samples
double timeout
Affine3d Tft_eff
unsigned int nJnt
const unsigned int m = 6
std::vector< std::string > nameJnt
KDL::Frame _des_eef_pose
KDL::Frame _current_eef_pose
KDL::Twist _des_eef_vel
geometry_msgs::msg::WrenchStamped _force
bool flagForce = false
bool _disable = true
bool _passThrough = false
KDL::JntArray _q_cur
KDL::JntArray _dq_cur
KDL::JntArray _q_cur_t
KDL::JntArray _dq_cur_t
KDL::Frame _frame_cur
KDL::Twist _twist_cur
std::vector< butterworth > posFilter
std::vector< butterworth > velFilter
std::vector< butterworth > jntFilter
std::unique_ptr< TransformUtility > trans
std::unique_ptr< KDL::ChainFkSolverPos_recursive > fk_solver_ptr
KDL::Chain chain
std::vector< KDL::Segment > chain_segs
std::shared_ptr< MyIK::MyIK > myik_solver_ptr
std::string root_frame
std::string chain_start
std::string chain_end
std::string urdf_param
std::string robot_ns = ""
std::string hw_config_ns = ""
Affine3d T_base_root
const int index = 0
rclcpp::Time _lastJntStateUpdate
Private Member Functions
void init (std::string robot)
void init (std::string robot, std::string hw_config)
bool getRosParams ()
bool resetService (const std::shared_ptr< std_srvs::srv::Trigger::Request > req, const std::shared_ptr< std_srvs::srv::Trigger::Response > &res)
Private Attributes
rclcpp::Node::SharedPtr node
double feedback_gain = 4.0
bool reseted = false
std::string header
rclcpp::Publisher< geometry_msgs::msg::WrenchStamped >::SharedPtr pubEefForce
std::mutex mtx_q
KDL::Frame des_eef_pose
KDL::Frame current_eef_pose
KDL::Twist des_eef_vel
KDL::JntArray q_cur
KDL::JntArray dq_cur
std_msgs::msg::Float64MultiArray cmd
Matrix3d userManipU
int rc
rclcpp::Client< std_srvs::srv::Trigger >::SharedPtr client
struct CartController::s_cbJntState s_cbJntState
struct CartController::s_moveInitPos s_moveInitPos
struct CartController::s_initCmd initCmd_
std::vector< double > _q_init_expect
std::string initPoseFrame
std::vector< double > initPose
std::string publisherTopicName
rclcpp::Service< std_srvs::srv::Trigger >::SharedPtr service
bool initialized = false
KDL::JntArray q_rest
rclcpp::Time prev_time
bool ftFound = false
const bool unique_state
Affine3d T_init
std::string ft_sensor_link
std::string ft_topic
Detailed Description
Definition at line 44 of file cart_controller.hpp.
Constructor & Destructor Documentation
CartController() [1/3]
CartController::CartController (rclcpp::Node::SharedPtr & node, const std::string robot, const std::string root_frame, const ControllerType controller, const double freq, const bool unique_state = false)
Definition at line 17 of file cart_controller.cpp.
References init(), and node.
CartController() [2/3]
CartController::CartController (rclcpp::Node::SharedPtr & node, const std::string robot, const std::string root_frame, const int index, const ControllerType controller, const double freq, const bool unique_state = false)
Definition at line 10 of file cart_controller.cpp.
References init(), and node.
CartController() [3/3]
CartController::CartController (rclcpp::Node::SharedPtr & node, const std::string robot, const std::string hw_config, const std::string root_frame, const int index, const ControllerType controller, const double freq, const bool unique_state = false)
Definition at line 3 of file cart_controller.cpp.
References init(), and node.
Member Function Documentation
cbForce()
void CartController::cbForce (const geometry_msgs::msg::WrenchStamped::SharedPtr msg) protected
Definition at line 364 of file cart_controller.cpp.
References _force, chain_end, flagForce, mtx, pubEefForce, Tft_eff, and geometry_msgs_utility::transformFT().
Referenced by init().
cbJntState()
void CartController::cbJntState (const sensor_msgs::msg::JointState::SharedPtr msg) protected
Definition at line 295 of file cart_controller.cpp.
References _dq_cur, _lastJntStateUpdate, _q_cur, chain_segs, dq_cur, flagJntState, initDesWithJnt(), initialized, initWithJnt(), CartController::s_cbJntState::isFirst, moveInitPos(), mtx_q, nameJnt, nJnt, node, and q_cur.
Referenced by init().
control()
int CartController::control ()
Definition at line 946 of file cart_controller.cpp.
References freq, node, starting(), stopping(), and update().
disableOperation()
void CartController::disableOperation () inline
Definition at line 285 of file cart_controller.hpp.
References _disable.
disablePoseFeedback()
void CartController::disablePoseFeedback () inline
Definition at line 390 of file cart_controller.hpp.
References myik_solver_ptr.
Referenced by getDesState().
enableOperation()
void CartController::enableOperation () inline
Definition at line 281 of file cart_controller.hpp.
References _disable.
enablePoseFeedback()
void CartController::enablePoseFeedback () inline
Definition at line 386 of file cart_controller.hpp.
Referenced by getDesState().
filterDesEffPoseVel()
void CartController::filterDesEffPoseVel (KDL::Frame & des_eef_pose, KDL::Twist & des_eef_vel) protected
Definition at line 646 of file cart_controller.cpp.
References des_eef_vel, and velFilter.
filterJnt()
void CartController::filterJnt (KDL::JntArray & q)
Definition at line 941 of file cart_controller.cpp.
References jntFilter, and nJnt.
Referenced by update().
getCartState()
void CartController::getCartState (KDL::Frame & frame, KDL::Twist & twist) inline
Definition at line 255 of file cart_controller.hpp.
References _frame_cur, and _twist_cur.
Referenced by getState().
getChainEnd()
std::string CartController::getChainEnd () const inline
Definition at line 302 of file cart_controller.hpp.
References chain_end.
getChainStart()
std::string CartController::getChainStart () const inline
Definition at line 298 of file cart_controller.hpp.
References chain_start.
Referenced by getInfo().
getDesired()
void CartController::getDesired (KDL::Frame & des_eef_pose, KDL::Twist & des_eef_vel) inline
Definition at line 380 of file cart_controller.hpp.
References _des_eef_pose, _des_eef_vel, des_eef_pose, and mtx.
getDesState()
void CartController::getDesState (const KDL::Frame & cur_pose, const KDL::Twist & cur_vel, KDL::Frame & des_pose, KDL::Twist & des_vel)
Definition at line 761 of file cart_controller.cpp.
References _des_eef_pose, _des_eef_vel, _disable, _passThrough, disablePoseFeedback(), enablePoseFeedback(), mtx, and node.
Referenced by getIKInput().
getForceEef()
geometry_msgs::msg::WrenchStamped CartController::getForceEef () inline
Definition at line 352 of file cart_controller.hpp.
References _force, and mtx.
Referenced by getForceEefVec().
getForceEefVec()
VectorXd CartController::getForceEefVec () inline
Definition at line 357 of file cart_controller.hpp.
References tf2::fromMsg(), and getForceEef().
getFtFound()
bool CartController::getFtFound () inline
Definition at line 406 of file cart_controller.hpp.
References ftFound.
getIKInput()
void CartController::getIKInput (double dt, KDL::JntArray & q_cur, KDL::Frame & des_eef_pose, KDL::Twist & des_eef_vel)
Definition at line 734 of file cart_controller.cpp.
References des_eef_pose, des_eef_vel, dq_cur, getDesState(), getState(), publishCurEffPoseVel(), publishDesEffPoseVel(), and q_cur.
Referenced by update().
getIndex()
int CartController::getIndex () inline
Definition at line 322 of file cart_controller.hpp.
References index.
getInfo()
void CartController::getInfo (std::string & chain_start, std::string & chain_end, Affine3d & T_base_root, std::shared_ptr< MyIK::MyIK > & myik) inline
Definition at line 292 of file cart_controller.hpp.
References chain_end, chain_start, getChainStart(), myik_solver_ptr, and T_base_root.
getInitCmd()
void CartController::getInitCmd (VectorXd & q_des_t, VectorXd & dq_des_t, KDL::JntArray & q_cur, int & lastLoop, double & T, double & s) inline
Definition at line 414 of file cart_controller.hpp.
References CartController::s_initCmd::dq_des_t, initCmd_, CartController::s_initCmd::lastLoop, q_cur, CartController::s_initCmd::q_cur, CartController::s_initCmd::q_des_t, CartController::s_initCmd::s, and CartController::s_initCmd::T.
getNameJnt()
std::vector< std::string > CartController::getNameJnt () inline
Definition at line 365 of file cart_controller.hpp.
References nameJnt.
getNJnt()
unsigned int CartController::getNJnt () inline
Definition at line 361 of file cart_controller.hpp.
References nJnt.
getNode()
rclcpp::Node::SharedPtr CartController::getNode () inline
Definition at line 410 of file cart_controller.hpp.
References node.
getOperationEnable()
bool CartController::getOperationEnable () const inline
Definition at line 289 of file cart_controller.hpp.
References _disable.
Referenced by publishState().
getqRest()
KDL::JntArray CartController::getqRest () inline
Definition at line 398 of file cart_controller.hpp.
References q_rest.
getReseted()
bool CartController::getReseted () inline
Definition at line 447 of file cart_controller.hpp.
References reseted.
getRobotNs()
std::string CartController::getRobotNs () const inline
Definition at line 318 of file cart_controller.hpp.
References robot_ns.
getRosParams()
bool CartController::getRosParams () private
Definition at line 120 of file cart_controller.cpp.
References _q_init_expect, chain_end, chain_start, RclcppUtility::declare_and_get_parameter(), RclcppUtility::declare_and_get_parameter_enum(), freq, ft_sensor_link, ft_topic, hw_config_ns, initPose, initPoseFrame, node, publisher, publisherTopicName, and solver.
Referenced by init().
getState() [1/2]
void CartController::getState (KDL::JntArray & q_cur, KDL::JntArray & dq_cur) inline
Definition at line 245 of file cart_controller.hpp.
References _dq_cur_t, _q_cur_t, and q_cur.
Referenced by getIKInput(), getState(), and getT_cur().
getState() [2/2]
void CartController::getState (KDL::JntArray & q_cur, KDL::JntArray & dq_cur, KDL::Frame & frame, KDL::Twist & twist) inline
Definition at line 250 of file cart_controller.hpp.
References dq_cur, getCartState(), getState(), and q_cur.
getT_base_world()
Affine3d CartController::getT_base_world () inline
Definition at line 348 of file cart_controller.hpp.
References myik_solver_ptr.
getT_cur()
Affine3d CartController::getT_cur () inline
Definition at line 331 of file cart_controller.hpp.
References dq_cur, getState(), JntToCart(), and q_cur.
Referenced by getT_root().
getT_init()
Affine3d CartController::getT_init () const inline
Definition at line 327 of file cart_controller.hpp.
References T_init.
getT_root()
Affine3d CartController::getT_root () inline
Definition at line 344 of file cart_controller.hpp.
References getT_cur(), and myik_solver_ptr.
getTft_eff()
Affine3d CartController::getTft_eff () inline
Definition at line 394 of file cart_controller.hpp.
References Tft_eff.
getTrajectoryCmd() [1/2]
void CartController::getTrajectoryCmd (const VectorXd & q_des, const double & T, trajectory_msgs::msg::JointTrajectory & cmd_trj) protected
Definition at line 553 of file cart_controller.cpp.
References nameJnt, nJnt, and node.
Referenced by sendTrajectoryCmd().
getTrajectoryCmd() [2/2]
void CartController::getTrajectoryCmd (const VectorXd & q_des, const VectorXd & dq_des, const double & T, trajectory_msgs::msg::JointTrajectory & cmd_trj) protected
Definition at line 566 of file cart_controller.cpp.
References nameJnt, and nJnt.
getTransform_base()
Affine3d CartController::getTransform_base (std::string target)
Definition at line 258 of file cart_controller.cpp.
References chain_start, and trans.
Referenced by init().
getVelocity()
void CartController::getVelocity (const KDL::Frame & frame, const KDL::Frame & prev_frame, const double & dt, KDL::Twist & twist) const
Definition at line 280 of file cart_controller.cpp.
References dt, and rotation_util::getQuaternionError().
init() [1/2]
void CartController::init (std::string robot) private
Definition at line 24 of file cart_controller.cpp.
References init().
Referenced by CartController(), and init().
init() [2/2]
void CartController::init (std::string robot, std::string hw_config) private
Definition at line 28 of file cart_controller.cpp.
References cbForce(), cbJntState(), chain_end, client, curStatePublisher, desStatePublisher, flagForce, flagJntState, freq, ft_sensor_link, ft_topic, ftFound, getRosParams(), getTransform_base(), gripperCmdPublisher, header, hw_config_ns, initMembers(), initPose, initPoseFrame, jntCmdPublisher, jntFilter, jntStateCmdPublisher, jntTrjCmdPublisher, nJnt, node, options, posFilter, pubEefForce, publisher, publisherTopicName, resetService(), robot_ns, service, subFlagPtrs, subForce, subJntState, T_init, Tft_eff, trans, unique_state, urdf_param, and velFilter.
initDesWithJnt()
void CartController::initDesWithJnt (const KDL::JntArray & q_init) protected
Definition at line 376 of file cart_controller.cpp.
References _des_eef_pose, _des_eef_vel, fk_solver_ptr, mtx, and q_cur.
Referenced by cbJntState().
initFt()
void CartController::initFt ()
Definition at line 715 of file cart_controller.cpp.
References ftFound, and resetFt().
initMembers()
void CartController::initMembers () protected
Definition at line 166 of file cart_controller.cpp.
References _q_cur, chain, chain_end, chain_segs, chain_start, dt, eps, fk_solver_ptr, freq, myik_solver_ptr, nJnt, node, robot_ns, root_frame, T_base_root, trans, unique_state, and urdf_param.
Referenced by init().
initWithJnt()
void CartController::initWithJnt (const KDL::JntArray & q_init) protected virtual
Definition at line 276 of file cart_controller.cpp.
Referenced by cbJntState().
isInitialized()
bool CartController::isInitialized () inline
Definition at line 369 of file cart_controller.hpp.
References initialized.
JntToCart() [1/2]
void CartController::JntToCart (const KDL::JntArray & q_in, const KDL::JntArray & dq_in, KDL::Frame & p_out, KDL::Twist & v_out) inline
Definition at line 310 of file cart_controller.hpp.
References myik_solver_ptr.
JntToCart() [2/2]
void CartController::JntToCart (const KDL::JntArray & q_in, KDL::Frame & p_out) inline
Definition at line 306 of file cart_controller.hpp.
References myik_solver_ptr.
Referenced by getT_cur(), and updateCurState().
JntVelToCartVel()
void CartController::JntVelToCartVel (const KDL::JntArray & q_in, const KDL::JntArray & dq_in, KDL::Twist & v_out) inline
Definition at line 314 of file cart_controller.hpp.
References myik_solver_ptr.
moveInitPos()
int CartController::moveInitPos (const KDL::JntArray & q_cur, const KDL::JntArray & dq_cur, const std::vector< std::string > nameJnt, std::vector< int > idxSegJnt) protected
Definition at line 382 of file cart_controller.cpp.
References _q_init_expect, dq_cur, CartController::s_initCmd::dq_des_t, dt, CartController::s_initCmd::flag, initCmd_, CartController::s_moveInitPos::isFirst, CartController::s_initCmd::lastLoop, mtx_q, myik_solver_ptr, nameJnt, nJnt, node, publisher, q_cur, CartController::s_initCmd::q_cur, CartController::s_moveInitPos::q_des, CartController::s_initCmd::q_des_t, CartController::s_moveInitPos::q_initial, q_rest, rc, robot_ns, CartController::s_initCmd::s, solver, CartController::s_initCmd::T, T_init, and CartController::s_moveInitPos::t_s.
Referenced by cbJntState().
publishCurEffPoseVel()
void CartController::publishCurEffPoseVel (const KDL::Frame & cur_eef_pose, const KDL::Twist & cur_eef_vel)
Definition at line 686 of file cart_controller.cpp.
References _force, curStatePublisher, mtx, and publishState().
Referenced by getIKInput().
publishDesEffPoseVel()
void CartController::publishDesEffPoseVel (const KDL::Frame & des_eef_pose, const KDL::Twist & des_eef_vel)
Definition at line 682 of file cart_controller.cpp.
References des_eef_pose, des_eef_vel, desStatePublisher, and publishState().
Referenced by getIKInput().
publishMarker()
void CartController::publishMarker (const KDL::JntArray q_cur)
Definition at line 691 of file cart_controller.cpp.
publishState() [1/2]
void CartController::publishState (const KDL::Frame & pose, const KDL::Twist & vel, const geometry_msgs::msg::Wrench & wrench, rclcpp::Publisher< ohrc_msgs::msg::State >::SharedPtr publisher)
Definition at line 659 of file cart_controller.cpp.
References getOperationEnable(), node, publisher, and tf2::toMsg().
publishState() [2/2]
void CartController::publishState (const KDL::Frame & pose, const KDL::Twist & vel, rclcpp::Publisher< ohrc_msgs::msg::State >::SharedPtr publisher)
Definition at line 655 of file cart_controller.cpp.
References publisher, and publishState().
Referenced by publishCurEffPoseVel(), publishDesEffPoseVel(), publishState(), and publishStates().
publishStates()
void CartController::publishStates ()
Definition at line 677 of file cart_controller.cpp.
References _des_eef_pose, _des_eef_vel, _force, _frame_cur, _twist_cur, curStatePublisher, desStatePublisher, mtx, and publishState().
resetFt()
void CartController::resetFt ()
Definition at line 263 of file cart_controller.cpp.
References client, and node.
Referenced by initFt(), and resetService().
resetPose()
void CartController::resetPose ()
Definition at line 246 of file cart_controller.cpp.
References initialized, CartController::s_cbJntState::isFirst, CartController::s_moveInitPos::isFirst, and node.
Referenced by resetService().
resetService()
bool CartController::resetService (const std::shared_ptr< std_srvs::srv::Trigger::Request > req, const std::shared_ptr< std_srvs::srv::Trigger::Response > & res) private
Definition at line 236 of file cart_controller.cpp.
References ftFound, resetFt(), and resetPose().
Referenced by init().
sendGripperCmd()
void CartController::sendGripperCmd ()
Definition at line 601 of file cart_controller.cpp.
References gripperCmd, and gripperCmdPublisher.
sendIntJntCmd() [1/3]
void CartController::sendIntJntCmd ()
Definition at line 518 of file cart_controller.cpp.
References initCmd_, mtx_q, and sendIntJntCmd().
Referenced by sendIntJntCmd().
sendIntJntCmd() [2/3]
void CartController::sendIntJntCmd (CartController::s_initCmd initCmd)
Definition at line 478 of file cart_controller.cpp.
References CartController::s_initCmd::dq_des_t, CartController::s_initCmd::flag, CartController::s_initCmd::lastLoop, node, publisher, q_cur, CartController::s_initCmd::q_cur, CartController::s_moveInitPos::q_des, CartController::s_initCmd::q_des_t, CartController::s_initCmd::s, sendJointStateCmd(), sendPositionCmd(), sendTrajectoryActionCmd(), sendTrajectoryCmd(), sendVelocityCmd(), and CartController::s_initCmd::T.
sendIntJntCmd() [3/3]
void CartController::sendIntJntCmd (VectorXd q_des_t, VectorXd dq_des_t, KDL::JntArray q_cur, bool lastLoop, double T, double s)
Definition at line 465 of file cart_controller.cpp.
References CartController::s_initCmd::dq_des_t, CartController::s_initCmd::flag, CartController::s_initCmd::lastLoop, q_cur, CartController::s_initCmd::q_cur, CartController::s_initCmd::q_des_t, CartController::s_initCmd::s, sendIntJntCmd(), and CartController::s_initCmd::T.
sendJointStateCmd()
void CartController::sendJointStateCmd (const VectorXd & q_des, const VectorXd & dq_des) protected
Definition at line 533 of file cart_controller.cpp.
References cmd, jntStateCmdPublisher, nameJnt, and node.
Referenced by sendIntJntCmd(), sendPosCmd(), and sendVelCmd().
sendPosCmd()
void CartController::sendPosCmd (const KDL::JntArray & q_des, const KDL::JntArray & dq_des, const double & dt)
Definition at line 895 of file cart_controller.cpp.
References dt, node, publisher, sendJointStateCmd(), sendPositionCmd(), sendTrajectoryCmd(), and sendVelocityCmd().
Referenced by update().
sendPositionCmd()
void CartController::sendPositionCmd (const VectorXd & q_des) protected
Definition at line 527 of file cart_controller.cpp.
References cmd, and jntCmdPublisher.
Referenced by sendIntJntCmd(), sendPosCmd(), sendVelCmd(), and sendVelocityCmd().
sendTrajectoryActionCmd() [1/2]
void CartController::sendTrajectoryActionCmd (const VectorXd & q_des, const double & T) protected
Definition at line 589 of file cart_controller.cpp.
Referenced by sendIntJntCmd().
sendTrajectoryActionCmd() [2/2]
void CartController::sendTrajectoryActionCmd (const VectorXd & q_des, const VectorXd & dq_des, const double & T) protected
Definition at line 594 of file cart_controller.cpp.
sendTrajectoryCmd() [1/2]
void CartController::sendTrajectoryCmd (const VectorXd & q_des, const double & T) protected
Definition at line 577 of file cart_controller.cpp.
References getTrajectoryCmd(), and jntTrjCmdPublisher.
Referenced by sendIntJntCmd(), sendPosCmd(), and sendVelCmd().
sendTrajectoryCmd() [2/2]
void CartController::sendTrajectoryCmd (const VectorXd & q_des, const VectorXd & dq_des, const double & T) protected
Definition at line 583 of file cart_controller.cpp.
References getTrajectoryCmd(), and jntTrjCmdPublisher.
sendVelCmd()
void CartController::sendVelCmd (const KDL::JntArray & q_des, const KDL::JntArray & dq_des, const double & dt)
Definition at line 918 of file cart_controller.cpp.
References dt, node, publisher, sendJointStateCmd(), sendPositionCmd(), sendTrajectoryCmd(), and sendVelocityCmd().
Referenced by update().
sendVelocityCmd() [1/2]
void CartController::sendVelocityCmd (const VectorXd & dq_des) protected
Definition at line 542 of file cart_controller.cpp.
References sendPositionCmd().
Referenced by sendIntJntCmd(), sendPosCmd(), sendVelCmd(), and sendVelocityCmd().
sendVelocityCmd() [2/2]
void CartController::sendVelocityCmd (const VectorXd & q_des, const VectorXd & dq_des, const KDL::JntArray & q_cur, const bool & lastLoop) protected
Definition at line 546 of file cart_controller.cpp.
References cmd, feedback_gain, q_cur, and sendVelocityCmd().
setDesired()
void CartController::setDesired (const KDL::Frame & des_eef_pose, const KDL::Twist & des_eef_vel) inline
Definition at line 373 of file cart_controller.hpp.
References des_eef_pose, des_eef_vel, and mtx.
setqRest()
void CartController::setqRest (const KDL::JntArray & q_rest) inline
Definition at line 402 of file cart_controller.hpp.
setReseted()
void CartController::setReseted (bool reseted) inline
Definition at line 450 of file cart_controller.hpp.
References reseted.
starting()
void CartController::starting (const rclcpp::Time & time)
Starts controller.
Parameters
time Current time
Definition at line 705 of file cart_controller.cpp.
References subscriber_utility::checkSubTopic(), mtx, node, robot_ns, and subFlagPtrs.
Referenced by control().
startOperation()
void CartController::startOperation () inline
Definition at line 276 of file cart_controller.hpp.
References _disable, and _passThrough.
stopping()
void CartController::stopping (const rclcpp::Time & time)
Stops controller.
Parameters
time Current time
Definition at line 726 of file cart_controller.cpp.
References cmd, controller, jntCmdPublisher, and nJnt.
Referenced by control().
update() [1/2]
void CartController::update ()
Updates controller, i.e. computes the odometry and sets the new velocity commands.
Parameters
time Current time
period Time since the last called to update
Definition at line 806 of file cart_controller.cpp.
References freq, node, and update().
Referenced by control(), and update().
update() [2/2]
void CartController::update (const rclcpp::Time & time, const rclcpp::Duration & period)
Definition at line 809 of file cart_controller.cpp.
References _userManipU, controller, des_eef_pose, des_eef_vel, dt, filterJnt(), getIKInput(), mtx, myik_solver_ptr, nJnt, node, prev_time, q_cur, rc, reseted, sendPosCmd(), sendVelCmd(), solver, and userManipU.
updateCurState()
void CartController::updateCurState () inline
Definition at line 232 of file cart_controller.hpp.
References _dq_cur, _dq_cur_t, _frame_cur, _lastJntStateUpdate, _q_cur, _twist_cur, JntToCart(), mtx_q, and node.
updateFilterCutoff()
void CartController::updateFilterCutoff (const double velFreq, const double jntFreq)
Definition at line 228 of file cart_controller.cpp.
References updateJntFilterCutoff(), and updateVelFilterCutoff().
updateJntFilterCutoff()
void CartController::updateJntFilterCutoff (const double jntFreq)
Definition at line 223 of file cart_controller.cpp.
References freq, jntFilter, and nJnt.
Referenced by updateFilterCutoff().
updatePosFilterCutoff()
void CartController::updatePosFilterCutoff (const double posFreq)
Definition at line 213 of file cart_controller.cpp.
References freq, and posFilter.
updateVelFilterCutoff()
void CartController::updateVelFilterCutoff (const double velFreq)
Definition at line 218 of file cart_controller.cpp.
References freq, and velFilter.
Referenced by updateFilterCutoff().
Member Data Documentation
_current_eef_pose
KDL::Frame CartController::_current_eef_pose protected
Definition at line 148 of file cart_controller.hpp.
_des_eef_pose
KDL::Frame CartController::_des_eef_pose protected
Definition at line 147 of file cart_controller.hpp.
Referenced by getDesired(), getDesState(), initDesWithJnt(), and publishStates().
_des_eef_vel
KDL::Twist CartController::_des_eef_vel protected
Definition at line 149 of file cart_controller.hpp.
Referenced by getDesired(), getDesState(), initDesWithJnt(), and publishStates().
_disable
bool CartController::_disable = true protected
Definition at line 154 of file cart_controller.hpp.
Referenced by disableOperation(), enableOperation(), getDesState(), getOperationEnable(), and startOperation().
_dq_cur
KDL::JntArray CartController::_dq_cur protected
Definition at line 156 of file cart_controller.hpp.
Referenced by cbJntState(), and updateCurState().
_dq_cur_t
KDL::JntArray CartController::_dq_cur_t protected
Definition at line 156 of file cart_controller.hpp.
Referenced by getState(), and updateCurState().
_force
geometry_msgs::msg::WrenchStamped CartController::_force protected
Definition at line 151 of file cart_controller.hpp.
Referenced by cbForce(), getForceEef(), publishCurEffPoseVel(), and publishStates().
_frame_cur
KDL::Frame CartController::_frame_cur protected
Definition at line 157 of file cart_controller.hpp.
Referenced by getCartState(), publishStates(), and updateCurState().
_lastJntStateUpdate
rclcpp::Time CartController::_lastJntStateUpdate protected
Definition at line 202 of file cart_controller.hpp.
Referenced by cbJntState(), and updateCurState().
_passThrough
bool CartController::_passThrough = false protected
Definition at line 154 of file cart_controller.hpp.
Referenced by getDesState(), and startOperation().
_q_cur
KDL::JntArray CartController::_q_cur protected
Definition at line 156 of file cart_controller.hpp.
Referenced by cbJntState(), initMembers(), and updateCurState().
_q_cur_t
KDL::JntArray CartController::_q_cur_t protected
Definition at line 156 of file cart_controller.hpp.
Referenced by getState().
_q_init_expect
std::vector<double> CartController::_q_init_expect private
Definition at line 93 of file cart_controller.hpp.
Referenced by getRosParams(), and moveInitPos().
_twist_cur
KDL::Twist CartController::_twist_cur protected
Definition at line 158 of file cart_controller.hpp.
Referenced by getCartState(), publishStates(), and updateCurState().
_userManipU
Matrix3d CartController::_userManipU = Matrix3d::Identity() protected
Definition at line 132 of file cart_controller.hpp.
Referenced by update().
chain
KDL::Chain CartController::chain protected
Definition at line 165 of file cart_controller.hpp.
Referenced by initMembers().
chain_end
std::string CartController::chain_end protected
Definition at line 172 of file cart_controller.hpp.
Referenced by cbForce(), getChainEnd(), getInfo(), getRosParams(), init(), and initMembers().
chain_segs
std::vector<KDL::Segment> CartController::chain_segs protected
Definition at line 166 of file cart_controller.hpp.
Referenced by cbJntState(), and initMembers().
chain_start
std::string CartController::chain_start protected
Definition at line 172 of file cart_controller.hpp.
Referenced by getChainStart(), getInfo(), getRosParams(), getTransform_base(), and initMembers().
client
rclcpp::Client<std_srvs::srv::Trigger>::SharedPtr CartController::client private
Definition at line 68 of file cart_controller.hpp.
Referenced by init(), and resetFt().
cmd
std_msgs::msg::Float64MultiArray CartController::cmd private
Definition at line 64 of file cart_controller.hpp.
Referenced by sendJointStateCmd(), sendPositionCmd(), sendVelocityCmd(), and stopping().
controller
ControllerType CartController::controller protected
Definition at line 120 of file cart_controller.hpp.
Referenced by stopping(), and update().
current_eef_pose
KDL::Frame CartController::current_eef_pose private
Definition at line 61 of file cart_controller.hpp.
curStatePublisher
rclcpp::Publisher<ohrc_msgs::msg::State>::SharedPtr CartController::curStatePublisher
Definition at line 435 of file cart_controller.hpp.
Referenced by init(), publishCurEffPoseVel(), and publishStates().
des_eef_pose
KDL::Frame CartController::des_eef_pose private
Definition at line 61 of file cart_controller.hpp.
Referenced by getDesired(), getIKInput(), publishDesEffPoseVel(), setDesired(), and update().
des_eef_vel
KDL::Twist CartController::des_eef_vel private
Definition at line 62 of file cart_controller.hpp.
Referenced by filterDesEffPoseVel(), getIKInput(), publishDesEffPoseVel(), setDesired(), and update().
desStatePublisher
rclcpp::Publisher<ohrc_msgs::msg::State>::SharedPtr CartController::desStatePublisher
Definition at line 435 of file cart_controller.hpp.
Referenced by init(), publishDesEffPoseVel(), and publishStates().
dq_cur
KDL::JntArray CartController::dq_cur private
Definition at line 63 of file cart_controller.hpp.
Referenced by cbJntState(), getIKInput(), getState(), getT_cur(), and moveInitPos().
dt
double CartController::dt
Definition at line 423 of file cart_controller.hpp.
Referenced by getVelocity(), initMembers(), moveInitPos(), sendPosCmd(), sendVelCmd(), and update().
eps
const double CartController::eps = 1e-6
Definition at line 426 of file cart_controller.hpp.
Referenced by initMembers().
feedback_gain
double CartController::feedback_gain = 4.0 private
Definition at line 47 of file cart_controller.hpp.
Referenced by sendVelocityCmd().
fk_solver_ptr
std::unique_ptr<KDL::ChainFkSolverPos_recursive> CartController::fk_solver_ptr protected
Definition at line 164 of file cart_controller.hpp.
Referenced by initDesWithJnt(), and initMembers().
flagArmMarker
bool CartController::flagArmMarker = false protected
Definition at line 133 of file cart_controller.hpp.
flagEffPose
bool CartController::flagEffPose = false protected
Definition at line 130 of file cart_controller.hpp.
flagForce
bool CartController::flagForce = false protected
Definition at line 152 of file cart_controller.hpp.
Referenced by cbForce(), and init().
flagJntState
bool CartController::flagJntState = false
Definition at line 439 of file cart_controller.hpp.
Referenced by cbJntState(), and init().
freq
double CartController::freq = 500.0
Definition at line 424 of file cart_controller.hpp.
Referenced by control(), getRosParams(), init(), initMembers(), update(), updateJntFilterCutoff(), updatePosFilterCutoff(), and updateVelFilterCutoff().
ft_sensor_link
std::string CartController::ft_sensor_link private
Definition at line 116 of file cart_controller.hpp.
Referenced by getRosParams(), and init().
ft_topic
std::string CartController::ft_topic private
Definition at line 116 of file cart_controller.hpp.
Referenced by getRosParams(), and init().
ftFound
bool CartController::ftFound = false private
Definition at line 111 of file cart_controller.hpp.
Referenced by getFtFound(), init(), initFt(), and resetService().
gripperCmd
float CartController::gripperCmd = 1.0
Definition at line 205 of file cart_controller.hpp.
Referenced by sendGripperCmd().
gripperCmdPublisher
rclcpp::Publisher<std_msgs::msg::Float64>::SharedPtr CartController::gripperCmdPublisher
Definition at line 432 of file cart_controller.hpp.
Referenced by init(), and sendGripperCmd().
header
std::string CartController::header private
Definition at line 52 of file cart_controller.hpp.
Referenced by init().
hw_config_ns
std::string CartController::hw_config_ns = "" protected
Definition at line 172 of file cart_controller.hpp.
Referenced by getRosParams(), and init().
index
const int CartController::index = 0 protected
Definition at line 189 of file cart_controller.hpp.
Referenced by getIndex().
initCmd_
struct CartController::s_initCmd CartController::initCmd_ private
Referenced by getInitCmd(), moveInitPos(), and sendIntJntCmd().
initialized
bool CartController::initialized = false private
Definition at line 105 of file cart_controller.hpp.
Referenced by cbJntState(), isInitialized(), and resetPose().
initPose
std::vector<double> CartController::initPose private
Definition at line 96 of file cart_controller.hpp.
Referenced by getRosParams(), and init().
initPoseFrame
std::string CartController::initPoseFrame private
Definition at line 95 of file cart_controller.hpp.
Referenced by getRosParams(), and init().
jntCmdPublisher
rclcpp::Publisher<std_msgs::msg::Float64MultiArray>::SharedPtr CartController::jntCmdPublisher
Definition at line 431 of file cart_controller.hpp.
Referenced by init(), sendPositionCmd(), and stopping().
jntFilter
std::vector<butterworth> CartController::jntFilter protected
Definition at line 160 of file cart_controller.hpp.
Referenced by filterJnt(), init(), and updateJntFilterCutoff().
jntStateCmdPublisher
rclcpp::Publisher<sensor_msgs::msg::JointState>::SharedPtr CartController::jntStateCmdPublisher
Definition at line 433 of file cart_controller.hpp.
Referenced by init(), and sendJointStateCmd().
jntTrjCmdPublisher
rclcpp::Publisher<trajectory_msgs::msg::JointTrajectory>::SharedPtr CartController::jntTrjCmdPublisher
Definition at line 434 of file cart_controller.hpp.
Referenced by init(), and sendTrajectoryCmd().
m
const unsigned int CartController::m = 6 protected
Definition at line 143 of file cart_controller.hpp.
mtx
std::mutex CartController::mtx
Definition at line 438 of file cart_controller.hpp.
Referenced by cbForce(), getDesired(), getDesState(), getForceEef(), initDesWithJnt(), publishCurEffPoseVel(), publishStates(), setDesired(), starting(), and update().
mtx_q
std::mutex CartController::mtx_q private
Definition at line 59 of file cart_controller.hpp.
Referenced by cbJntState(), moveInitPos(), sendIntJntCmd(), and updateCurState().
myik_solver_ptr
std::shared_ptr<MyIK::MyIK> CartController::myik_solver_ptr protected
Definition at line 169 of file cart_controller.hpp.
Referenced by disablePoseFeedback(), getInfo(), getT_base_world(), getT_root(), initMembers(), JntToCart(), JntVelToCartVel(), moveInitPos(), and update().
nameJnt
std::vector<std::string> CartController::nameJnt protected
Definition at line 145 of file cart_controller.hpp.
Referenced by cbJntState(), getNameJnt(), getTrajectoryCmd(), moveInitPos(), and sendJointStateCmd().
nJnt
unsigned int CartController::nJnt protected
Definition at line 142 of file cart_controller.hpp.
Referenced by cbJntState(), filterJnt(), getNJnt(), getTrajectoryCmd(), init(), initMembers(), moveInitPos(), stopping(), update(), and updateJntFilterCutoff().
node
rclcpp::Node::SharedPtr CartController::node private
Definition at line 45 of file cart_controller.hpp.
Referenced by CartController(), cbJntState(), control(), getDesState(), getNode(), getRosParams(), getTrajectoryCmd(), init(), initMembers(), moveInitPos(), publishState(), resetFt(), resetPose(), sendIntJntCmd(), sendJointStateCmd(), sendPosCmd(), sendVelCmd(), starting(), update(), and updateCurState().
num_samples
int CartController::num_samples protected
Definition at line 136 of file cart_controller.hpp.
options
rclcpp::SubscriptionOptions CartController::options
Definition at line 216 of file cart_controller.hpp.
Referenced by init().
posFilter
std::vector<butterworth> CartController::posFilter protected
Definition at line 160 of file cart_controller.hpp.
Referenced by init(), and updatePosFilterCutoff().
prev_time
rclcpp::Time CartController::prev_time private
Definition at line 109 of file cart_controller.hpp.
Referenced by update().
pubEefForce
rclcpp::Publisher<geometry_msgs::msg::WrenchStamped>::SharedPtr CartController::pubEefForce private
Definition at line 57 of file cart_controller.hpp.
Referenced by cbForce(), and init().
publisher
PublisherType CartController::publisher protected
Definition at line 121 of file cart_controller.hpp.
Referenced by getRosParams(), init(), moveInitPos(), publishState(), sendIntJntCmd(), sendPosCmd(), and sendVelCmd().
publisherTopicName
std::string CartController::publisherTopicName private
Definition at line 99 of file cart_controller.hpp.
Referenced by getRosParams(), and init().
q_cur
KDL::JntArray CartController::q_cur private
Definition at line 63 of file cart_controller.hpp.
Referenced by cbJntState(), getIKInput(), getInitCmd(), getState(), getT_cur(), initDesWithJnt(), moveInitPos(), sendIntJntCmd(), sendVelocityCmd(), and update().
q_rest
KDL::JntArray CartController::q_rest private
Definition at line 107 of file cart_controller.hpp.
Referenced by getqRest(), and moveInitPos().
rc
int CartController::rc private
Definition at line 66 of file cart_controller.hpp.
Referenced by moveInitPos(), and update().
reseted
bool CartController::reseted = false private
Definition at line 48 of file cart_controller.hpp.
Referenced by getReseted(), setReseted(), and update().
robot_ns
std::string CartController::robot_ns = "" protected
Definition at line 172 of file cart_controller.hpp.
Referenced by getRobotNs(), init(), initMembers(), moveInitPos(), and starting().
root_frame
std::string CartController::root_frame protected
Definition at line 171 of file cart_controller.hpp.
Referenced by initMembers().
s_cbJntState
struct CartController::s_cbJntState CartController::s_cbJntState private
s_moveInitPos
struct CartController::s_moveInitPos CartController::s_moveInitPos private
service
rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr CartController::service private
Definition at line 102 of file cart_controller.hpp.
Referenced by init().
solver
SolverType CartController::solver protected
Definition at line 119 of file cart_controller.hpp.
Referenced by getRosParams(), moveInitPos(), and update().
subFlagPtrs
std::vector<bool*> CartController::subFlagPtrs protected
Definition at line 128 of file cart_controller.hpp.
Referenced by init(), and starting().
subForce
rclcpp::Subscription<geometry_msgs::msg::WrenchStamped>::SharedPtr CartController::subForce protected
Definition at line 125 of file cart_controller.hpp.
Referenced by init().
subJntState
rclcpp::Subscription<sensor_msgs::msg::JointState>::SharedPtr CartController::subJntState protected
Definition at line 124 of file cart_controller.hpp.
Referenced by init().
T_base_root
Affine3d CartController::T_base_root protected
Definition at line 173 of file cart_controller.hpp.
Referenced by getInfo(), and initMembers().
T_init
Affine3d CartController::T_init private
Definition at line 114 of file cart_controller.hpp.
Referenced by getT_init(), init(), and moveInitPos().
Tft_eff
Affine3d CartController::Tft_eff protected
Definition at line 140 of file cart_controller.hpp.
Referenced by cbForce(), getTft_eff(), and init().
timeout
double CartController::timeout protected
Definition at line 138 of file cart_controller.hpp.
trans
std::unique_ptr<TransformUtility> CartController::trans protected
Definition at line 162 of file cart_controller.hpp.
Referenced by getTransform_base(), init(), and initMembers().
unique_state
const bool CartController::unique_state private
Definition at line 112 of file cart_controller.hpp.
Referenced by init(), and initMembers().
urdf_param
std::string CartController::urdf_param protected
Definition at line 172 of file cart_controller.hpp.
Referenced by init(), and initMembers().
useManipOpt
bool CartController::useManipOpt = false protected
Definition at line 134 of file cart_controller.hpp.
userManipU
Matrix3d CartController::userManipU private
Definition at line 65 of file cart_controller.hpp.
Referenced by update().
velFilter
std::vector<butterworth> CartController::velFilter protected
Definition at line 160 of file cart_controller.hpp.
Referenced by filterDesEffPoseVel(), init(), and updateVelFilterCutoff().
The documentation for this class was generated from the following files:
cart_controller.hpp
cart_controller.cpp