OpenHRC: geometry_msgs_utility::Wrench Class Reference
geometry_msgs_utility::Wrench Class Reference
#include <Wrench.h>
Classes
struct paramLPF
Public Member Functions
Wrench (paramLPF param_LPF)
Wrench (paramLPF param_LPF, paramDeadZone param_DeadZone)
~Wrench ()
void LPF (geometry_msgs::msg::Wrench raw_wrench, geometry_msgs::msg::Wrench &filtered_wrench)
void diff (geometry_msgs::msg::Wrench wrench, geometry_msgs::msg::Wrench &diff_wrench)
void diff_LPF (geometry_msgs::msg::Wrench wrench, geometry_msgs::msg::Wrench &filtered_wrench)
void deadZone_LPF (geometry_msgs::msg::Wrench raw_wrench, geometry_msgs::msg::Wrench &filtered_wrench)
Public Attributes
paramDeadZone m_paramDeadZone
Private Member Functions
void LPF_initialize (int order, double cutoff_freq, double sampling_freq)
Private Attributes
double delta_t
std::vector< std::unique_ptr< geometry_msgs_utility::Vector3 > > _filter_vec
Detailed Description
Definition at line 60 of file Wrench.h.
Constructor & Destructor Documentation
Wrench() [1/2]
geometry_msgs_utility::Wrench::Wrench (paramLPF param_LPF)
Definition at line 11 of file Wrench.cpp.
References geometry_msgs_utility::Wrench::paramLPF::cutoff_freq, delta_t, LPF_initialize(), geometry_msgs_utility::Wrench::paramLPF::order, and geometry_msgs_utility::Wrench::paramLPF::sampling_freq.
Wrench() [2/2]
geometry_msgs_utility::Wrench::Wrench (paramLPF param_LPF, paramDeadZone param_DeadZone)
Definition at line 16 of file Wrench.cpp.
References geometry_msgs_utility::Wrench::paramLPF::cutoff_freq, delta_t, LPF_initialize(), m_paramDeadZone, geometry_msgs_utility::Wrench::paramLPF::order, and geometry_msgs_utility::Wrench::paramLPF::sampling_freq.
~Wrench()
geometry_msgs_utility::Wrench::~Wrench ()
Definition at line 23 of file Wrench.cpp.
Member Function Documentation
deadZone_LPF()
void geometry_msgs_utility::Wrench::deadZone_LPF (geometry_msgs::msg::Wrench raw_wrench, geometry_msgs::msg::Wrench & filtered_wrench)
Definition at line 70 of file Wrench.cpp.
References geometry_msgs_utility::deadZone(), LPF(), and m_paramDeadZone.
Referenced by geometry_msgs_utility::WrenchStamped::deadZone_LPF().
diff()
void geometry_msgs_utility::Wrench::diff (geometry_msgs::msg::Wrench wrench, geometry_msgs::msg::Wrench & diff_wrench)
Definition at line 40 of file Wrench.cpp.
References delta_t.
Referenced by diff_LPF().
diff_LPF()
void geometry_msgs_utility::Wrench::diff_LPF (geometry_msgs::msg::Wrench wrench, geometry_msgs::msg::Wrench & filtered_wrench)
Definition at line 53 of file Wrench.cpp.
References diff(), and LPF().
LPF()
void geometry_msgs_utility::Wrench::LPF (geometry_msgs::msg::Wrench raw_wrench, geometry_msgs::msg::Wrench & filtered_wrench)
Definition at line 35 of file Wrench.cpp.
References _filter_vec.
Referenced by deadZone_LPF(), diff_LPF(), and geometry_msgs_utility::WrenchStamped::LPF().
LPF_initialize()
void geometry_msgs_utility::Wrench::LPF_initialize (int order, double cutoff_freq, double sampling_freq) private
Definition at line 29 of file Wrench.cpp.
References _filter_vec.
Referenced by Wrench().
Member Data Documentation
_filter_vec
std::vector<std::unique_ptr<geometry_msgs_utility::Vector3> > geometry_msgs_utility::Wrench::_filter_vec private
Definition at line 71 of file Wrench.h.
Referenced by LPF(), and LPF_initialize().
delta_t
double geometry_msgs_utility::Wrench::delta_t private
Definition at line 70 of file Wrench.h.
Referenced by diff(), and Wrench().
m_paramDeadZone
paramDeadZone geometry_msgs_utility::Wrench::m_paramDeadZone
Definition at line 67 of file Wrench.h.
Referenced by deadZone_LPF(), and Wrench().
The documentation for this class was generated from the following files:
Wrench.h
Wrench.cpp