OpenHRC: AdmittanceController Class Reference
AdmittanceController Class Reference
#include <admittance_controller.hpp>
Classes
struct ImpCoeff
struct ImpParam
Public Member Functions
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
virtual void initInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Private Member Functions
void getCriticalDampingCoeff (ImpCoeff &impCoeff, const std::vector< bool > &isGotMDK)
ImpParam getImpParam (const ImpCoeff &impCoeff)
ImpCoeff getImpCoeff ()
VectorXd getControlState (const VectorXd &x, const VectorXd &xd, const VectorXd &exForce, const double dt, const ImpParam &impParam)
Private Attributes
VectorXd x
VectorXd xd
struct AdmittanceController::ImpParam impParam
Affine3d restPose
bool skipMass = false
bool variable = false
std::unique_ptr< math_utility::Integrator > integrator
std::function< VectorXd(const double &t, const VectorXd &, const std::unordered_map< std::string, Eigen::MatrixXd > &)> f_dx
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Detailed Description
Definition at line 6 of file admittance_controller.hpp.
Member Function Documentation
getControlState()
VectorXd AdmittanceController::getControlState (const VectorXd & x, const VectorXd & xd, const VectorXd & exForce, const double dt, const ImpParam & impParam) private
Definition at line 114 of file admittance_controller.cpp.
References f_dx, integrator, skipMass, variable, x, and xd.
Referenced by updateTargetPose().
getCriticalDampingCoeff()
void AdmittanceController::getCriticalDampingCoeff (ImpCoeff & impCoeff, const std::vector< bool > & isGotMDK) private
Definition at line 8 of file admittance_controller.cpp.
References AdmittanceController::ImpCoeff::d, AdmittanceController::ImpCoeff::d_, AdmittanceController::ImpCoeff::k, AdmittanceController::ImpCoeff::k_, AdmittanceController::ImpCoeff::m, and AdmittanceController::ImpCoeff::m_.
getImpCoeff()
AdmittanceController::ImpCoeff AdmittanceController::getImpCoeff () private
Definition at line 24 of file admittance_controller.cpp.
References Interface::controller, AdmittanceController::ImpCoeff::d, AdmittanceController::ImpCoeff::d_, RclcppUtility::declare_and_get_parameter(), Interface::interfaceName, AdmittanceController::ImpCoeff::k, AdmittanceController::ImpCoeff::k_, AdmittanceController::ImpCoeff::m, AdmittanceController::ImpCoeff::m_, Interface::node, and skipMass.
Referenced by initInterface().
getImpParam()
AdmittanceController::ImpParam AdmittanceController::getImpParam (const ImpCoeff & impCoeff) private
Definition at line 75 of file admittance_controller.cpp.
References AdmittanceController::ImpCoeff::d, Interface::dt, f_dx, impParam, integrator, AdmittanceController::ImpCoeff::k, AdmittanceController::ImpCoeff::m, Interface::node, math_utility::Integrator::RungeKutta, skipMass, variable, and x.
Referenced by initInterface().
initInterface()
void AdmittanceController::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file admittance_controller.cpp.
References getImpCoeff(), getImpParam(), and impParam.
Interface() [1/2]
Interface::Interface (const std::shared_ptr< CartController > & controller) inline
Definition at line 57 of file interface.hpp.
Interface() [2/2]
Interface::Interface (const std::shared_ptr< CartController > & controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode) inline
Definition at line 60 of file interface.hpp.
updateTargetPose()
void AdmittanceController::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 134 of file admittance_controller.cpp.
References Interface::controller, tf2::fromMsg(), getControlState(), restPose, Interface::taskState, x, and xd.
Member Data Documentation
f_dx
std::function<VectorXd(const double& t, const VectorXd&, const std::unordered_map<std::string, Eigen::MatrixXd>&)> AdmittanceController::f_dx private
Definition at line 28 of file admittance_controller.hpp.
Referenced by getControlState(), and getImpParam().
impParam
struct AdmittanceController::ImpParam AdmittanceController::impParam private
Referenced by getImpParam(), and initInterface().
integrator
std::unique_ptr<math_utility::Integrator> AdmittanceController::integrator private
Definition at line 27 of file admittance_controller.hpp.
Referenced by getControlState(), and getImpParam().
restPose
Affine3d AdmittanceController::restPose private
Definition at line 23 of file admittance_controller.hpp.
Referenced by updateTargetPose().
skipMass
bool AdmittanceController::skipMass = false private
Definition at line 24 of file admittance_controller.hpp.
Referenced by getControlState(), getImpCoeff(), and getImpParam().
variable
bool AdmittanceController::variable = false private
Definition at line 25 of file admittance_controller.hpp.
Referenced by getControlState(), and getImpParam().
x
VectorXd AdmittanceController::x private
Definition at line 7 of file admittance_controller.hpp.
Referenced by getControlState(), getImpParam(), and updateTargetPose().
xd
VectorXd AdmittanceController::xd private
Definition at line 7 of file admittance_controller.hpp.
Referenced by getControlState(), and updateTargetPose().
The documentation for this class was generated from the following files:
admittance_controller.hpp
admittance_controller.cpp