OpenHRC: TwistTopicInterface Class Reference
TwistTopicInterface Class Reference
#include <twist_topic_interface.hpp>
Public Member Functions
TwistTopicInterface (const std::shared_ptr< CartController > &controller)
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
void resetInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Protected Member Functions
void cbTwist (const geometry_msgs::msg::Twist::SharedPtr msg)
virtual void setSubscriber ()
void setPoseFromTwistMsg (const geometry_msgs::msg::Twist &twist_msg, KDL::Frame &pos, KDL::Twist &twist)
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes
bool _flagTopic = false
Affine3d T
Matrix3d R
bool isFirst = true
ohrc_msgs::msg::State state
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Private Attributes
rclcpp::Subscription< geometry_msgs::msg::Twist >::SharedPtr subTwist
geometry_msgs::msg::Twist _twist
double k_trans = 1.0
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 8 of file twist_topic_interface.hpp.
Constructor & Destructor Documentation
TwistTopicInterface()
TwistTopicInterface::TwistTopicInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 30 of file twist_topic_interface.hpp.
Member Function Documentation
cbTwist()
void TwistTopicInterface::cbTwist (const geometry_msgs::msg::Twist::SharedPtr msg) protected
Definition at line 21 of file twist_topic_interface.cpp.
References _flagTopic, _twist, Interface::mtx, and Interface::updateIsEnable().
Referenced by setSubscriber().
initInterface()
void TwistTopicInterface::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file twist_topic_interface.cpp.
References Interface::controller, RclcppUtility::declare_and_get_parameter(), Interface::interfaceName, k_trans, Interface::node, R, setSubscriber(), and Interface::stateFrameId.
Interface() [1/2]
Interface::Interface (const std::shared_ptr< CartController > & controller) inline
Definition at line 57 of file interface.hpp.
Interface() [2/2]
Interface::Interface (const std::shared_ptr< CartController > & controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode) inline
Definition at line 60 of file interface.hpp.
resetInterface()
void TwistTopicInterface::resetInterface () override virtual
Reimplemented from Interface.
Definition at line 80 of file twist_topic_interface.cpp.
References isFirst, and state.
setPoseFromTwistMsg()
void TwistTopicInterface::setPoseFromTwistMsg (const geometry_msgs::msg::Twist & twist_msg, KDL::Frame & pos, KDL::Twist & twist) protected
Definition at line 29 of file twist_topic_interface.cpp.
References Interface::controller, Interface::dt, tf2::fromMsg(), isFirst, k_trans, R, state, T, and tf2::toMsg().
Referenced by JoyTopicInterface::updateTargetPose(), and updateTargetPose().
setSubscriber()
void TwistTopicInterface::setSubscriber () protected virtual
Reimplemented in JoyTopicInterface.
Definition at line 14 of file twist_topic_interface.cpp.
References cbTwist(), Interface::controller, Interface::getTopicAndFrameName(), Interface::node, Interface::stateTopicName, and subTwist.
Referenced by initInterface().
updateTargetPose()
void TwistTopicInterface::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Reimplemented in JoyTopicInterface.
Definition at line 68 of file twist_topic_interface.cpp.
References _flagTopic, _twist, Interface::mtx, and setPoseFromTwistMsg().
Member Data Documentation
_flagTopic
bool TwistTopicInterface::_flagTopic = false protected
Definition at line 15 of file twist_topic_interface.hpp.
Referenced by JoyTopicInterface::cbJoy(), cbTwist(), JoyTopicInterface::updateTargetPose(), and updateTargetPose().
_twist
geometry_msgs::msg::Twist TwistTopicInterface::_twist private
Definition at line 10 of file twist_topic_interface.hpp.
Referenced by cbTwist(), and updateTargetPose().
isFirst
bool TwistTopicInterface::isFirst = true protected
Definition at line 19 of file twist_topic_interface.hpp.
Referenced by resetInterface(), and setPoseFromTwistMsg().
k_trans
double TwistTopicInterface::k_trans = 1.0 private
Definition at line 12 of file twist_topic_interface.hpp.
Referenced by initInterface(), and setPoseFromTwistMsg().
R
Matrix3d TwistTopicInterface::R protected
Definition at line 18 of file twist_topic_interface.hpp.
Referenced by JoyTopicInterface::initInterface(), initInterface(), and setPoseFromTwistMsg().
state
ohrc_msgs::msg::State TwistTopicInterface::state protected
Definition at line 21 of file twist_topic_interface.hpp.
Referenced by resetInterface(), and setPoseFromTwistMsg().
subTwist
rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr TwistTopicInterface::subTwist private
Definition at line 9 of file twist_topic_interface.hpp.
Referenced by setSubscriber().
T
Affine3d TwistTopicInterface::T protected
Definition at line 17 of file twist_topic_interface.hpp.
Referenced by setPoseFromTwistMsg().
The documentation for this class was generated from the following files:
twist_topic_interface.hpp
twist_topic_interface.cpp