OpenHRC: geometry_msgs_utility::Vector3 Class Reference
geometry_msgs_utility::Vector3 Class Reference
#include <Vector3.h>
Public Member Functions
void LPF (geometry_msgs::msg::Vector3 raw_point, geometry_msgs::msg::Vector3 &filtered_point)
void diff (geometry_msgs::msg::Vector3 point, geometry_msgs::msg::Vector3 &diff_point)
void diff_LPF (geometry_msgs::msg::Vector3 point, geometry_msgs::msg::Vector3 &filtered_point)
double dist (geometry_msgs::msg::Vector3 point1, geometry_msgs::msg::Vector3 point2)
Vector3 (int order, double cutoff_freq, double sampling_freq)
~Vector3 ()
Private Attributes
double delta_t
std::vector< std::unique_ptr< butterworth > > _filter
Detailed Description
Definition at line 9 of file Vector3.h.
Constructor & Destructor Documentation
Vector3()
geometry_msgs_utility::Vector3::Vector3 (int order, double cutoff_freq, double sampling_freq)
Definition at line 11 of file Vector3.cpp.
References _filter, and delta_t.
~Vector3()
geometry_msgs_utility::Vector3::~Vector3 ()
Definition at line 18 of file Vector3.cpp.
Member Function Documentation
diff()
void geometry_msgs_utility::Vector3::diff (geometry_msgs::msg::Vector3 point, geometry_msgs::msg::Vector3 & diff_point)
Definition at line 30 of file Vector3.cpp.
References delta_t.
Referenced by diff_LPF().
diff_LPF()
void geometry_msgs_utility::Vector3::diff_LPF (geometry_msgs::msg::Vector3 point, geometry_msgs::msg::Vector3 & filtered_point)
Definition at line 38 of file Vector3.cpp.
References diff(), and LPF().
dist()
double geometry_msgs_utility::Vector3::dist (geometry_msgs::msg::Vector3 point1, geometry_msgs::msg::Vector3 point2)
Definition at line 44 of file Vector3.cpp.
LPF()
void geometry_msgs_utility::Vector3::LPF (geometry_msgs::msg::Vector3 raw_point, geometry_msgs::msg::Vector3 & filtered_point)
Definition at line 24 of file Vector3.cpp.
References _filter.
Referenced by diff_LPF().
Member Data Documentation
_filter
std::vector<std::unique_ptr<butterworth> > geometry_msgs_utility::Vector3::_filter private
Definition at line 12 of file Vector3.h.
Referenced by LPF(), and Vector3().
delta_t
double geometry_msgs_utility::Vector3::delta_t private
Definition at line 11 of file Vector3.h.
Referenced by diff(), and Vector3().
The documentation for this class was generated from the following files:
Vector3.h
Vector3.cpp