OpenHRC: CartTrajectoryImpedanceController Class Reference
CartTrajectoryImpedanceController Class Reference
#include <cart_trajectory_impedance_controller.hpp>
Public Member Functions
void initInterface () override final
void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override final
Public Member Functions inherited from ImpedanceController
virtual void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
virtual void initInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Private Member Functions
bool updateImpedanceTarget (const VectorXd &x, VectorXd &xd) override
void setSubscriber () override final
void cbTargetPoses (const geometry_msgs::PoseArray::ConstPtr &msg) override final
bool getTrajectories (const geometry_msgs::PoseArray &targetPoses, std::vector< moveit_msgs::CartesianTrajectory > &trjs)
Private Attributes
ros::ServiceClient client
std::vector< moveit_msgs::CartesianTrajectory > _trjs
bool _flagTrjs = false
int targetIdx = 0
int nTrjs = 0
moveit_msgs::CartesianTrajectory trj
bool updateTrjs = true
int t_i = 0
int forward = 1
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Member Functions inherited from ImpedanceController
virtual void setSubscriber ()
virtual bool updateImpedanceTarget (const VectorXd &x, VectorXd &xd)
TaskState updataTaskState (const VectorXd &delta_x, const int targetIdx)
virtual bool checkTargetReached (const VectorXd &delta_x, const VectorXd &force)
virtual bool checkRestTargetReached (const VectorXd &delta_x, const VectorXd &force)
virtual void cbTargetPoses (const geometry_msgs::PoseArray::ConstPtr &msg)
ros::Duration getTrialTime ()
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes inherited from ImpedanceController
std::mutex mtx_imp
ros::Publisher RespawnReqPublisher
ros::Publisher targetDistPublisher
int stack = 0
Affine3d restPose
std::vector< Affine3d > _targetPoses
double timeLimit = 30.0
double forceLimit = 100.0
double posThr = 0.01
double velThr = 0.01
double forceThr = -0.01
double posThr_r = 0.01
double velThr_r = 0.01
double forceThr_r = -0.01
bool repeat = true
bool restEverytime = true
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Detailed Description
Definition at line 10 of file cart_trajectory_impedance_controller.hpp.
Member Function Documentation
cbTargetPoses()
void CartTrajectoryImpedanceController::cbTargetPoses (const geometry_msgs::PoseArray::ConstPtr & msg) final override private virtual
Reimplemented from ImpedanceController.
Definition at line 8 of file cart_trajectory_impedance_controller.cpp.
References _flagTrjs, ImpedanceController::_targetPoses, _trjs, tf2::fromMsg(), getTrajectories(), and ImpedanceController::mtx_imp.
getTrajectories()
bool CartTrajectoryImpedanceController::getTrajectories (const geometry_msgs::PoseArray & targetPoses, std::vector< moveit_msgs::CartesianTrajectory > & trjs) private
Definition at line 19 of file cart_trajectory_impedance_controller.cpp.
References client, tf2::fromMsg(), ImpedanceController::restPose, and tf2::toMsg().
Referenced by cbTargetPoses().
initInterface()
void CartTrajectoryImpedanceController::initInterface () final override virtual
Reimplemented from ImpedanceController.
Definition at line 3 of file cart_trajectory_impedance_controller.cpp.
References client, and ImpedanceController::initInterface().
setSubscriber()
void CartTrajectoryImpedanceController::setSubscriber () inline final override private virtual
Reimplemented from ImpedanceController.
Definition at line 25 of file cart_trajectory_impedance_controller.hpp.
References ImpedanceController::setSubscriber().
updateImpedanceTarget()
bool CartTrajectoryImpedanceController::updateImpedanceTarget (const VectorXd & x, VectorXd & xd) override private virtual
Reimplemented from ImpedanceController.
Definition at line 39 of file cart_trajectory_impedance_controller.cpp.
References _flagTrjs, ImpedanceController::_targetPoses, _trjs, forward, tf2::fromMsg(), ImpedanceController::getTrialTime(), ImpedanceController::mtx_imp, nTrjs, ImpedanceController::restPose, t_i, targetIdx, Interface::taskState, trj, ImpedanceController::updataTaskState(), updateTrjs, and ImpedanceController::xd.
updateTargetPose()
void CartTrajectoryImpedanceController::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) inline final override virtual
Reimplemented from ImpedanceController.
Definition at line 40 of file cart_trajectory_impedance_controller.hpp.
References ImpedanceController::updateTargetPose().
Member Data Documentation
_flagTrjs
bool CartTrajectoryImpedanceController::_flagTrjs = false private
Definition at line 13 of file cart_trajectory_impedance_controller.hpp.
Referenced by cbTargetPoses(), and updateImpedanceTarget().
_trjs
std::vector<moveit_msgs::CartesianTrajectory> CartTrajectoryImpedanceController::_trjs private
Definition at line 12 of file cart_trajectory_impedance_controller.hpp.
Referenced by cbTargetPoses(), and updateImpedanceTarget().
client
ros::ServiceClient CartTrajectoryImpedanceController::client private
Definition at line 11 of file cart_trajectory_impedance_controller.hpp.
Referenced by getTrajectories(), and initInterface().
forward
int CartTrajectoryImpedanceController::forward = 1 private
Definition at line 21 of file cart_trajectory_impedance_controller.hpp.
Referenced by updateImpedanceTarget().
nTrjs
int CartTrajectoryImpedanceController::nTrjs = 0 private
Definition at line 15 of file cart_trajectory_impedance_controller.hpp.
Referenced by updateImpedanceTarget().
t_i
int CartTrajectoryImpedanceController::t_i = 0 private
Definition at line 20 of file cart_trajectory_impedance_controller.hpp.
Referenced by updateImpedanceTarget().
targetIdx
int CartTrajectoryImpedanceController::targetIdx = 0 private
Definition at line 14 of file cart_trajectory_impedance_controller.hpp.
Referenced by updateImpedanceTarget().
trj
moveit_msgs::CartesianTrajectory CartTrajectoryImpedanceController::trj private
Definition at line 17 of file cart_trajectory_impedance_controller.hpp.
Referenced by updateImpedanceTarget().
updateTrjs
bool CartTrajectoryImpedanceController::updateTrjs = true private
Definition at line 18 of file cart_trajectory_impedance_controller.hpp.
Referenced by updateImpedanceTarget().
The documentation for this class was generated from the following files:
cart_trajectory_impedance_controller.hpp
cart_trajectory_impedance_controller.cpp