OpenHRC: StateTopicInterface Class Reference
StateTopicInterface Class Reference
#include <state_topic_interface.hpp>
Public Member Functions
StateTopicInterface (const std::shared_ptr< CartController > &controller)
void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Protected Member Functions
void cbState (const ohrc_msgs::msg::State::SharedPtr msg)
virtual void modifyTargetState (ohrc_msgs::msg::State &state)
virtual void setSubscriber ()
void getTargetState (const ohrc_msgs::msg::State &state, KDL::Frame &pos, KDL::Twist &twist)
void resetInterface () override
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes
rclcpp::Subscription< ohrc_msgs::msg::State >::SharedPtr subState
Affine3d T_state_base
double k_trans = 1.0
Affine3d T
Affine3d T_start
Affine3d T_state_start
bool isFirst = true
ohrc_msgs::msg::State _state
bool _flagTopic = false
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 7 of file state_topic_interface.hpp.
Constructor & Destructor Documentation
StateTopicInterface()
StateTopicInterface::StateTopicInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 28 of file state_topic_interface.hpp.
Member Function Documentation
cbState()
void StateTopicInterface::cbState (const ohrc_msgs::msg::State::SharedPtr msg) protected
Definition at line 17 of file state_topic_interface.cpp.
References _state, Interface::isEnable, Interface::mtx, and Interface::reset().
Referenced by setSubscriber().
getTargetState()
void StateTopicInterface::getTargetState (const ohrc_msgs::msg::State & state, KDL::Frame & pos, KDL::Twist & twist) protected
Definition at line 27 of file state_topic_interface.cpp.
References Interface::controller, tf2::fromMsg(), isFirst, k_trans, T, T_start, T_state_base, and T_state_start.
Referenced by updateTargetPose(), and XrBodyInterface::updateTargetPose().
initInterface()
void StateTopicInterface::initInterface () override virtual
Reimplemented from Interface.
Reimplemented in XrBodyInterface.
Definition at line 3 of file state_topic_interface.cpp.
References Interface::controller, RclcppUtility::declare_and_get_parameter(), Interface::interfaceName, k_trans, Interface::node, setSubscriber(), Interface::stateFrameId, and T_state_base.
Referenced by OmegaInterface::initInterface().
Interface() [1/2]
Interface::Interface (const std::shared_ptr< CartController > & controller) inline
Definition at line 57 of file interface.hpp.
Interface() [2/2]
Interface::Interface (const std::shared_ptr< CartController > & controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode) inline
Definition at line 60 of file interface.hpp.
modifyTargetState()
virtual void StateTopicInterface::modifyTargetState (ohrc_msgs::msg::State & state) inline protected virtual
Definition at line 20 of file state_topic_interface.hpp.
Referenced by updateTargetPose().
resetInterface()
void StateTopicInterface::resetInterface () override protected virtual
Reimplemented from Interface.
Definition at line 67 of file state_topic_interface.cpp.
References isFirst.
setSubscriber()
void StateTopicInterface::setSubscriber () protected virtual
Reimplemented in XrBodyInterface.
Definition at line 11 of file state_topic_interface.cpp.
References cbState(), Interface::controller, Interface::getTopicAndFrameName(), Interface::node, Interface::stateTopicName, and subState.
Referenced by initInterface().
updateTargetPose()
void StateTopicInterface::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Reimplemented in XrBodyInterface.
Definition at line 71 of file state_topic_interface.cpp.
References _state, getTargetState(), modifyTargetState(), and Interface::mtx.
Member Data Documentation
_flagTopic
bool StateTopicInterface::_flagTopic = false protected
Definition at line 17 of file state_topic_interface.hpp.
Referenced by XrBodyInterface::cbBody(), and XrBodyInterface::updateTargetPose().
_state
ohrc_msgs::msg::State StateTopicInterface::_state protected
Definition at line 16 of file state_topic_interface.hpp.
Referenced by cbState(), and updateTargetPose().
isFirst
bool StateTopicInterface::isFirst = true protected
Definition at line 14 of file state_topic_interface.hpp.
Referenced by getTargetState(), and resetInterface().
k_trans
double StateTopicInterface::k_trans = 1.0 protected
Definition at line 11 of file state_topic_interface.hpp.
Referenced by getTargetState(), and initInterface().
subState
rclcpp::Subscription<ohrc_msgs::msg::State>::SharedPtr StateTopicInterface::subState protected
Definition at line 9 of file state_topic_interface.hpp.
Referenced by setSubscriber().
T
Affine3d StateTopicInterface::T protected
Definition at line 13 of file state_topic_interface.hpp.
Referenced by getTargetState().
T_start
Affine3d StateTopicInterface::T_start protected
Definition at line 13 of file state_topic_interface.hpp.
Referenced by getTargetState().
T_state_base
Affine3d StateTopicInterface::T_state_base protected
Definition at line 10 of file state_topic_interface.hpp.
Referenced by OmegaInterface::feedback(), getTargetState(), initInterface(), and XrBodyInterface::initInterface().
T_state_start
Affine3d StateTopicInterface::T_state_start protected
Definition at line 13 of file state_topic_interface.hpp.
Referenced by getTargetState().
The documentation for this class was generated from the following files:
state_topic_interface.hpp
state_topic_interface.cpp