OpenHRC: JoyTopicInterface Class Reference
JoyTopicInterface Class Reference
#include <joy_topic_interface.hpp>
Public Member Functions
JoyTopicInterface (const std::shared_ptr< CartController > &controller)
void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
TwistTopicInterface (const std::shared_ptr< CartController > &controller)
Public Member Functions inherited from TwistTopicInterface
TwistTopicInterface (const std::shared_ptr< CartController > &controller)
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
void resetInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Protected Member Functions
void cbJoy (const sensor_msgs::msg::Joy::SharedPtr msg)
void setSubscriber () override
Protected Member Functions inherited from TwistTopicInterface
void cbTwist (const geometry_msgs::msg::Twist::SharedPtr msg)
virtual void setSubscriber ()
void setPoseFromTwistMsg (const geometry_msgs::msg::Twist &twist_msg, KDL::Frame &pos, KDL::Twist &twist)
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Private Types
enum class GripperOperation { Keep , Switch , None }
Private Attributes
rclcpp::Subscription< sensor_msgs::msg::Joy >::SharedPtr subJoy
sensor_msgs::msg::Joy _joy
double gain_h = 0.1
double gain_r = 0.1
int gripper_idx = 0
enum JoyTopicInterface::GripperOperation gripperOperation
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Attributes inherited from TwistTopicInterface
bool _flagTopic = false
Affine3d T
Matrix3d R
bool isFirst = true
ohrc_msgs::msg::State state
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Detailed Description
Definition at line 7 of file joy_topic_interface.hpp.
Member Enumeration Documentation
GripperOperation
enum class JoyTopicInterface::GripperOperation strong private
Enumerator
Keep
Switch
None
Definition at line 13 of file joy_topic_interface.hpp.
Constructor & Destructor Documentation
JoyTopicInterface()
JoyTopicInterface::JoyTopicInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 23 of file joy_topic_interface.hpp.
Member Function Documentation
cbJoy()
void JoyTopicInterface::cbJoy (const sensor_msgs::msg::Joy::SharedPtr msg) protected
Definition at line 21 of file joy_topic_interface.cpp.
References TwistTopicInterface::_flagTopic, _joy, Interface::mtx, and Interface::updateIsEnable().
Referenced by setSubscriber().
initInterface()
void JoyTopicInterface::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file joy_topic_interface.cpp.
References Interface::controller, RclcppUtility::declare_and_get_parameter(), gain_h, gain_r, Interface::interfaceName, Interface::node, TwistTopicInterface::R, setSubscriber(), and Interface::stateFrameId.
setSubscriber()
void JoyTopicInterface::setSubscriber () override protected virtual
Reimplemented from TwistTopicInterface.
Definition at line 13 of file joy_topic_interface.cpp.
References cbJoy(), Interface::controller, RclcppUtility::declare_and_get_parameter(), RclcppUtility::declare_and_get_parameter_enum(), Interface::getTopicAndFrameName(), gripper_idx, gripperOperation, Interface::node, Interface::robot_ns, Interface::stateTopicName, subJoy, and Switch.
Referenced by initInterface().
TwistTopicInterface()
TwistTopicInterface::TwistTopicInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 30 of file twist_topic_interface.hpp.
updateTargetPose()
void JoyTopicInterface::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from TwistTopicInterface.
Definition at line 30 of file joy_topic_interface.cpp.
References TwistTopicInterface::_flagTopic, _joy, Interface::controller, gain_h, gain_r, gripper_idx, gripperOperation, Keep, Interface::mtx, TwistTopicInterface::setPoseFromTwistMsg(), and Switch.
Member Data Documentation
_joy
sensor_msgs::msg::Joy JoyTopicInterface::_joy private
Definition at line 9 of file joy_topic_interface.hpp.
Referenced by cbJoy(), and updateTargetPose().
gain_h
double JoyTopicInterface::gain_h = 0.1 private
Definition at line 11 of file joy_topic_interface.hpp.
Referenced by initInterface(), and updateTargetPose().
gain_r
double JoyTopicInterface::gain_r = 0.1 private
Definition at line 11 of file joy_topic_interface.hpp.
Referenced by initInterface(), and updateTargetPose().
gripper_idx
int JoyTopicInterface::gripper_idx = 0 private
Definition at line 12 of file joy_topic_interface.hpp.
Referenced by setSubscriber(), and updateTargetPose().
gripperOperation
enum JoyTopicInterface::GripperOperation JoyTopicInterface::gripperOperation private
Referenced by setSubscriber(), and updateTargetPose().
subJoy
rclcpp::Subscription<sensor_msgs::msg::Joy>::SharedPtr JoyTopicInterface::subJoy private
Definition at line 8 of file joy_topic_interface.hpp.
Referenced by setSubscriber().
The documentation for this class was generated from the following files:
joy_topic_interface.hpp
joy_topic_interface.cpp