OpenHRC: ImpedanceController Class Reference
ImpedanceController Class Reference
#include <impedance_controller.hpp>
Classes
struct ImpCoeff
struct ImpParam
Public Member Functions
virtual void updateTargetPose (KDL::Frame &pose, KDL::Twist &twist) override
virtual void initInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Protected Member Functions
virtual void setSubscriber ()
virtual bool updateImpedanceTarget (const VectorXd &x, VectorXd &xd)
TaskState updataTaskState (const VectorXd &delta_x, const int targetIdx)
virtual bool checkTargetReached (const VectorXd &delta_x, const VectorXd &force)
virtual bool checkRestTargetReached (const VectorXd &delta_x, const VectorXd &force)
virtual void cbTargetPoses (const geometry_msgs::PoseArray::ConstPtr &msg)
ros::Duration getTrialTime ()
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes
std::mutex mtx_imp
ros::Publisher RespawnReqPublisher
ros::Publisher targetDistPublisher
int stack = 0
Affine3d restPose
std::vector< Affine3d > _targetPoses
double timeLimit = 30.0
double forceLimit = 100.0
double posThr = 0.01
double velThr = 0.01
double forceThr = -0.01
double posThr_r = 0.01
double velThr_r = 0.01
double forceThr_r = -0.01
bool repeat = true
bool restEverytime = true
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Private Member Functions
void getParam ()
void getCriticalDampingCoeff (ImpCoeff &impCoeff, const std::vector< bool > &isGotMDK)
ImpParam getImpParam (const ImpCoeff &impCoeff)
ImpCoeff getImpCoeff ()
Affine3d getNextTarget (const TaskState &taskState, const std::vector< Affine3d > &targetPoses, const Affine3d &restPose, int &targetIdx, int &nextTargetIdx)
VectorXd getControlState (const VectorXd &x, const VectorXd &xd, const VectorXd &exForce, const double dt, const ImpParam &impParam)
bool NormReachedCheck (const VectorXd &delta_x, const VectorXd &force, const double posThr, const double velThr, const double forceThr)
Private Attributes
ros::Subscriber targetSubscriber
bool _targetUpdated = false
int nextTargetIdx = -1
VectorXd x
VectorXd xd
struct ImpedanceController::ImpParam impParam
ros::Subscriber subTarget
ros::Time t_start
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 10 of file impedance_controller.hpp.
Member Function Documentation
cbTargetPoses()
void ImpedanceController::cbTargetPoses (const geometry_msgs::PoseArray::ConstPtr & msg) protected virtual
Reimplemented in CartTrajectoryImpedanceController.
Definition at line 124 of file impedance_controller.cpp.
References _targetPoses, _targetUpdated, tf2::fromMsg(), and mtx_imp.
Referenced by setSubscriber().
checkRestTargetReached()
bool ImpedanceController::checkRestTargetReached (const VectorXd & delta_x, const VectorXd & force) protected virtual
Definition at line 143 of file impedance_controller.cpp.
References forceThr_r, NormReachedCheck(), posThr_r, and velThr_r.
Referenced by updataTaskState().
checkTargetReached()
bool ImpedanceController::checkTargetReached (const VectorXd & delta_x, const VectorXd & force) protected virtual
Definition at line 139 of file impedance_controller.cpp.
References forceThr, NormReachedCheck(), posThr, and velThr.
Referenced by updataTaskState().
getControlState()
VectorXd ImpedanceController::getControlState (const VectorXd & x, const VectorXd & xd, const VectorXd & exForce, const double dt, const ImpParam & impParam) private
Definition at line 179 of file impedance_controller.cpp.
References ImpedanceController::ImpParam::A, ImpedanceController::ImpParam::B, ImpedanceController::ImpParam::C, Interface::dt, impParam, x, and xd.
Referenced by updateTargetPose().
getCriticalDampingCoeff()
void ImpedanceController::getCriticalDampingCoeff (ImpCoeff & impCoeff, const std::vector< bool > & isGotMDK) private
Definition at line 59 of file impedance_controller.cpp.
References ImpedanceController::ImpCoeff::d, ImpedanceController::ImpCoeff::d_, ImpedanceController::ImpCoeff::k, ImpedanceController::ImpCoeff::k_, ImpedanceController::ImpCoeff::m, and ImpedanceController::ImpCoeff::m_.
Referenced by getImpCoeff().
getImpCoeff()
ImpedanceController::ImpCoeff ImpedanceController::getImpCoeff () private
Definition at line 75 of file impedance_controller.cpp.
References Interface::controller, ImpedanceController::ImpCoeff::d, ImpedanceController::ImpCoeff::d_, getCriticalDampingCoeff(), ImpedanceController::ImpCoeff::k, ImpedanceController::ImpCoeff::k_, ImpedanceController::ImpCoeff::m, and ImpedanceController::ImpCoeff::m_.
Referenced by initInterface().
getImpParam()
ImpedanceController::ImpParam ImpedanceController::getImpParam (const ImpCoeff & impCoeff) private
Definition at line 106 of file impedance_controller.cpp.
References ImpedanceController::ImpParam::A, ImpedanceController::ImpParam::B, ImpedanceController::ImpParam::C, ImpedanceController::ImpCoeff::d, impParam, ImpedanceController::ImpCoeff::k, and ImpedanceController::ImpCoeff::m.
Referenced by initInterface().
getNextTarget()
Affine3d ImpedanceController::getNextTarget (const TaskState & taskState, const std::vector< Affine3d > & targetPoses, const Affine3d & restPose, int & targetIdx, int & nextTargetIdx) private
Definition at line 183 of file impedance_controller.cpp.
References nextTargetIdx, repeat, restEverytime, restPose, Interface::targetIdx, and Interface::taskState.
Referenced by updateImpedanceTarget().
getParam()
void ImpedanceController::getParam () private
Definition at line 14 of file impedance_controller.cpp.
References Interface::controller, forceLimit, forceThr, forceThr_r, posThr, posThr_r, repeat, restEverytime, Interface::targetName, timeLimit, velThr, and velThr_r.
Referenced by initInterface().
getTrialTime()
ros::Duration ImpedanceController::getTrialTime () inline protected
Definition at line 62 of file impedance_controller.hpp.
References t_start.
Referenced by updataTaskState(), and CartTrajectoryImpedanceController::updateImpedanceTarget().
initInterface()
void ImpedanceController::initInterface () override virtual
Reimplemented from Interface.
Reimplemented in CartTrajectoryImpedanceController.
Definition at line 3 of file impedance_controller.cpp.
References Interface::controller, getImpCoeff(), getImpParam(), getParam(), impParam, RespawnReqPublisher, setSubscriber(), targetDistPublisher, and Interface::targetName.
Referenced by CartTrajectoryImpedanceController::initInterface().
Interface() [1/2]
Interface::Interface (const std::shared_ptr< CartController > & controller) inline
Definition at line 57 of file interface.hpp.
Interface() [2/2]
Interface::Interface (const std::shared_ptr< CartController > & controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode) inline
Definition at line 60 of file interface.hpp.
NormReachedCheck()
bool ImpedanceController::NormReachedCheck (const VectorXd & delta_x, const VectorXd & force, const double posThr, const double velThr, const double forceThr) private
Definition at line 130 of file impedance_controller.cpp.
References forceThr, posThr, and velThr.
Referenced by checkRestTargetReached(), and checkTargetReached().
setSubscriber()
void ImpedanceController::setSubscriber () protected virtual
Reimplemented in CartTrajectoryImpedanceController.
Definition at line 55 of file impedance_controller.cpp.
References cbTargetPoses(), Interface::targetName, and targetSubscriber.
Referenced by initInterface(), and CartTrajectoryImpedanceController::setSubscriber().
updataTaskState()
TaskState ImpedanceController::updataTaskState (const VectorXd & delta_x, const int targetIdx) protected
Definition at line 147 of file impedance_controller.cpp.
References Interface::blocked, checkRestTargetReached(), checkTargetReached(), Interface::controller, tf2::fromMsg(), getTrialTime(), Interface::nCompletedTask, RespawnReqPublisher, t_start, Interface::targetIdx, Interface::taskState, and timeLimit.
Referenced by updateImpedanceTarget(), and CartTrajectoryImpedanceController::updateImpedanceTarget().
updateImpedanceTarget()
bool ImpedanceController::updateImpedanceTarget (const VectorXd & x, VectorXd & xd) protected virtual
Reimplemented in CartTrajectoryImpedanceController.
Definition at line 207 of file impedance_controller.cpp.
References _targetPoses, _targetUpdated, Interface::controller, getNextTarget(), mtx_imp, nextTargetIdx, restPose, Interface::targetIdx, Interface::taskState, updataTaskState(), and xd.
Referenced by updateTargetPose().
updateTargetPose()
void ImpedanceController::updateTargetPose (KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented in CartTrajectoryImpedanceController.
Definition at line 233 of file impedance_controller.cpp.
References Interface::controller, tf2::fromMsg(), getControlState(), restPose, t_start, Interface::targetDistance, targetDistPublisher, Interface::taskState, updateImpedanceTarget(), x, and xd.
Referenced by CartTrajectoryImpedanceController::updateTargetPose().
Member Data Documentation
_targetPoses
std::vector<Affine3d> ImpedanceController::_targetPoses protected
Definition at line 47 of file impedance_controller.hpp.
Referenced by cbTargetPoses(), CartTrajectoryImpedanceController::cbTargetPoses(), updateImpedanceTarget(), and CartTrajectoryImpedanceController::updateImpedanceTarget().
_targetUpdated
bool ImpedanceController::_targetUpdated = false private
Definition at line 13 of file impedance_controller.hpp.
Referenced by cbTargetPoses(), and updateImpedanceTarget().
forceLimit
double ImpedanceController::forceLimit = 100.0 protected
Definition at line 48 of file impedance_controller.hpp.
Referenced by getParam().
forceThr
double ImpedanceController::forceThr = -0.01 protected
Definition at line 49 of file impedance_controller.hpp.
Referenced by checkTargetReached(), getParam(), and NormReachedCheck().
forceThr_r
double ImpedanceController::forceThr_r = -0.01 protected
Definition at line 50 of file impedance_controller.hpp.
Referenced by checkRestTargetReached(), and getParam().
impParam
struct ImpedanceController::ImpParam ImpedanceController::impParam private
Referenced by getControlState(), getImpParam(), and initInterface().
mtx_imp
std::mutex ImpedanceController::mtx_imp protected
Definition at line 43 of file impedance_controller.hpp.
Referenced by cbTargetPoses(), CartTrajectoryImpedanceController::cbTargetPoses(), updateImpedanceTarget(), and CartTrajectoryImpedanceController::updateImpedanceTarget().
nextTargetIdx
int ImpedanceController::nextTargetIdx = -1 private
Definition at line 15 of file impedance_controller.hpp.
Referenced by getNextTarget(), and updateImpedanceTarget().
posThr
double ImpedanceController::posThr = 0.01 protected
Definition at line 49 of file impedance_controller.hpp.
Referenced by checkTargetReached(), getParam(), and NormReachedCheck().
posThr_r
double ImpedanceController::posThr_r = 0.01 protected
Definition at line 50 of file impedance_controller.hpp.
Referenced by checkRestTargetReached(), and getParam().
repeat
bool ImpedanceController::repeat = true protected
Definition at line 51 of file impedance_controller.hpp.
Referenced by getNextTarget(), and getParam().
RespawnReqPublisher
ros::Publisher ImpedanceController::RespawnReqPublisher protected
Definition at line 44 of file impedance_controller.hpp.
Referenced by initInterface(), and updataTaskState().
restEverytime
bool ImpedanceController::restEverytime = true protected
Definition at line 51 of file impedance_controller.hpp.
Referenced by getNextTarget(), and getParam().
restPose
Affine3d ImpedanceController::restPose protected
Definition at line 46 of file impedance_controller.hpp.
Referenced by getNextTarget(), CartTrajectoryImpedanceController::getTrajectories(), updateImpedanceTarget(), CartTrajectoryImpedanceController::updateImpedanceTarget(), and updateTargetPose().
stack
int ImpedanceController::stack = 0 protected
Definition at line 45 of file impedance_controller.hpp.
subTarget
ros::Subscriber ImpedanceController::subTarget private
Definition at line 27 of file impedance_controller.hpp.
t_start
ros::Time ImpedanceController::t_start private
Definition at line 29 of file impedance_controller.hpp.
Referenced by getTrialTime(), updataTaskState(), and updateTargetPose().
targetDistPublisher
ros::Publisher ImpedanceController::targetDistPublisher protected
Definition at line 44 of file impedance_controller.hpp.
Referenced by initInterface(), and updateTargetPose().
targetSubscriber
ros::Subscriber ImpedanceController::targetSubscriber private
Definition at line 11 of file impedance_controller.hpp.
Referenced by setSubscriber().
timeLimit
double ImpedanceController::timeLimit = 30.0 protected
Definition at line 48 of file impedance_controller.hpp.
Referenced by getParam(), and updataTaskState().
velThr
double ImpedanceController::velThr = 0.01 protected
Definition at line 49 of file impedance_controller.hpp.
Referenced by checkTargetReached(), getParam(), and NormReachedCheck().
velThr_r
double ImpedanceController::velThr_r = 0.01 protected
Definition at line 50 of file impedance_controller.hpp.
Referenced by checkRestTargetReached(), and getParam().
x
VectorXd ImpedanceController::x private
Definition at line 17 of file impedance_controller.hpp.
Referenced by getControlState(), and updateTargetPose().
xd
VectorXd ImpedanceController::xd private
Definition at line 17 of file impedance_controller.hpp.
Referenced by getControlState(), updateImpedanceTarget(), CartTrajectoryImpedanceController::updateImpedanceTarget(), and updateTargetPose().
The documentation for this class was generated from the following files:
impedance_controller.hpp
impedance_controller.cpp