OpenHRC: OhrcController Class Reference
OhrcController Class Reference
#include <ohrc_controller.hpp>
Public Member Functions
OhrcController ()
~OhrcController ()
void control ()
rclcpp::executors::MultiThreadedExecutor::SharedPtr getExecutor ()
Protected Member Functions
virtual void defineInterface ()
virtual void initControllerAdditional ()
virtual void overrideDesired (std::vector< KDL::Frame > &desPose, std::vector< KDL::Twist > &desVel)
size_t getNRobot ()
Protected Attributes
rclcpp::SubscriptionOptions options
int priorityIdx = 0
std::vector< Interfaces > interfaces
std::vector< std::shared_ptr< CartController > > cartControllers
Private Types
enum class MFMode { Individual , Parallel , Cooperation , None }
enum class IKMode { Concatenated , Order , Parallel , None }
enum class PriorityType { Manual , Automation , Adaptation , None }
Private Member Functions
bool getRosParams (std::vector< std::string > &robots, std::vector< std::string > &hw_configs)
void initMenbers (const std::vector< std::string > robots, const std::vector< std::string > hw_configs)
void updateDesired ()
void resetService (const std::shared_ptr< std_srvs::srv::SetBool::Request > req, const std::shared_ptr< std_srvs::srv::SetBool::Response > &res)
void priorityService (const std::shared_ptr< ohrc_msgs::srv::SetPriority::Request > req, const std::shared_ptr< ohrc_msgs::srv::SetPriority::Response > &res)
void publishState (const rclcpp::Time &time, const std::vector< KDL::Frame > curPose, const std::vector< KDL::Twist > curVel, const std::vector< KDL::Frame > desPose, const std::vector< KDL::Twist > desVel)
void controlLoop ()
virtual void starting ()
void stopping ()
void update (const rclcpp::Time &time, const rclcpp::Duration &period)
bool initRobotPose ()
void initController ()
void setPriority (PriorityType priority)
void setPriority (std::vector< int > idx)
void setPriority (int i)
void setLowPriority (int i)
void setHightLowPriority (int high, int low)
virtual void runLoopEnd ()
void updateTargetPoseInterface (KDL::Frame &pose, KDL::Twist &twist, Interfaces &interfaces_, KDL::Frame &prev_pose)
void updateTargetPoseBase (KDL::Frame &pose, KDL::Twist &twist, Interfaces &interfaces_)
void updateAllCurState ()
void initInterface (const std::vector< std::shared_ptr< Interface > > interfaces_)
void resetInterface (const std::vector< std::shared_ptr< Interface > > interfaces_)
void feedback (KDL::Frame &pose, KDL::Twist &twist, const std::vector< std::shared_ptr< Interface > > interfaces_)
void selectInterface (std::vector< bool > isEnable)
Private Attributes
rclcpp::executors::MultiThreadedExecutor exec
std::vector< rclcpp::Node::SharedPtr > nodes
rclcpp::Node::SharedPtr node
bool isStarted = false
bool isControllerInitialized = false
std::vector< std::shared_ptr< MyIK::MyIK > > myik_ptr
rclcpp::TimerBase::SharedPtr control_timer
rclcpp::Service< std_srvs::srv::SetBool >::SharedPtr resetServer
rclcpp::Service< ohrc_msgs::srv::SetPriority >::SharedPtr priorityServer
enum OhrcController::MFMode MFmode
enum OhrcController::IKMode IKmode
int nRobot = 0
bool unique_state = false
std::string root_frame
double freq = 500.0
double dt
rclcpp::Time t0
std::string date
std::unique_ptr< MyIK::MyIK > multimyik_solver_ptr
ControllerType controller
PublisherType publisher
std::vector< int > manualInd
std::vector< int > autoInd
std::vector< rclcpp::Time > prev_time
enum OhrcController::PriorityType priority
bool adaptation = false
std::string adaptationOption_
std::vector< bool > _isEnable
std::vector< KDL::Frame > prev_desPose
Detailed Description
Definition at line 20 of file ohrc_controller.hpp.
Member Enumeration Documentation
IKMode
enum class OhrcController::IKMode strong private
Enumerator
Concatenated
Order
Parallel
None
Definition at line 53 of file ohrc_controller.hpp.
MFMode
enum class OhrcController::MFMode strong private
Enumerator
Individual
Parallel
Cooperation
None
Definition at line 52 of file ohrc_controller.hpp.
PriorityType
enum class OhrcController::PriorityType strong private
Enumerator
Manual
Automation
Adaptation
None
Definition at line 76 of file ohrc_controller.hpp.
Constructor & Destructor Documentation
OhrcController()
OhrcController::OhrcController ()
Definition at line 3 of file ohrc_controller.cpp.
~OhrcController()
OhrcController::~OhrcController ()
Definition at line 6 of file ohrc_controller.cpp.
References stopping().
Member Function Documentation
control()
void OhrcController::control ()
Definition at line 516 of file ohrc_controller.cpp.
References exec, getRosParams(), initMenbers(), and node.
Referenced by main().
controlLoop()
void OhrcController::controlLoop () private
Definition at line 474 of file ohrc_controller.cpp.
References cartControllers, Concatenated, dt, IKmode, initController(), initRobotPose(), isControllerInitialized, isStarted, nRobot, Order, Parallel, starting(), update(), updateAllCurState(), and updateDesired().
Referenced by initMenbers().
defineInterface()
virtual void OhrcController::defineInterface () inline protected virtual
Reimplemented in SingleInterface< T >, and MultiInterface.
Definition at line 121 of file ohrc_controller.hpp.
Referenced by initMenbers().
feedback()
void OhrcController::feedback (KDL::Frame & pose, KDL::Twist & twist, const std::vector< std::shared_ptr< Interface > > interfaces_) private
Definition at line 216 of file ohrc_controller.cpp.
Referenced by update().
getExecutor()
rclcpp::executors::MultiThreadedExecutor::SharedPtr OhrcController::getExecutor () inline
Definition at line 144 of file ohrc_controller.hpp.
References exec.
getNRobot()
size_t OhrcController::getNRobot () inline protected
Definition at line 135 of file ohrc_controller.hpp.
References nRobot.
Referenced by SingleInterface< T >::defineInterface(), and MultiInterface::defineInterface().
getRosParams()
bool OhrcController::getRosParams (std::vector< std::string > & robots, std::vector< std::string > & hw_configs) private
Definition at line 10 of file ohrc_controller.cpp.
References Concatenated, controller, RclcppUtility::declare_and_get_parameter(), RclcppUtility::declare_and_get_parameter_enum(), freq, IKmode, Individual, Manual, MFmode, node, priority, root_frame, and unique_state.
Referenced by control().
initController()
void OhrcController::initController () private
Definition at line 293 of file ohrc_controller.cpp.
References cartControllers, interfaces, multimyik_solver_ptr, nRobot, resetInterface(), t0, and updateAllCurState().
Referenced by controlLoop().
initControllerAdditional()
virtual void OhrcController::initControllerAdditional () inline protected virtual
Definition at line 122 of file ohrc_controller.hpp.
Referenced by initMenbers().
initInterface()
void OhrcController::initInterface (const std::vector< std::shared_ptr< Interface > > interfaces_) private
Definition at line 204 of file ohrc_controller.cpp.
References _isEnable.
Referenced by initMenbers().
initMenbers()
void OhrcController::initMenbers (const std::vector< std::string > robots, const std::vector< std::string > hw_configs) private
Definition at line 73 of file ohrc_controller.cpp.
References autoInd, cartControllers, control_timer, controller, controlLoop(), defineInterface(), dt, exec, freq, initControllerAdditional(), initInterface(), interfaces, manualInd, multimyik_solver_ptr, myik_ptr, node, nodes, nRobot, options, prev_desPose, prev_time, priority, priorityServer, priorityService(), resetServer, resetService(), root_frame, ohrc_control::selectBaseController(), setPriority(), and unique_state.
Referenced by control().
initRobotPose()
bool OhrcController::initRobotPose () private
Definition at line 439 of file ohrc_controller.cpp.
References cartControllers, math_utility::concatenateVecOfVec(), nRobot, unique_state, and updateAllCurState().
Referenced by controlLoop().
overrideDesired()
virtual void OhrcController::overrideDesired (std::vector< KDL::Frame > & desPose, std::vector< KDL::Twist > & desVel) inline protected virtual
Definition at line 130 of file ohrc_controller.hpp.
Referenced by updateDesired().
priorityService()
void OhrcController::priorityService (const std::shared_ptr< ohrc_msgs::srv::SetPriority::Request > req, const std::shared_ptr< ohrc_msgs::srv::SetPriority::Response > & res) private
Definition at line 235 of file ohrc_controller.cpp.
References priorityIdx.
Referenced by initMenbers().
publishState()
void OhrcController::publishState (const rclcpp::Time & time, const std::vector< KDL::Frame > curPose, const std::vector< KDL::Twist > curVel, const std::vector< KDL::Frame > desPose, const std::vector< KDL::Twist > desVel) private
Definition at line 322 of file ohrc_controller.cpp.
References cartControllers, and nRobot.
resetInterface()
void OhrcController::resetInterface (const std::vector< std::shared_ptr< Interface > > interfaces_) private
Definition at line 211 of file ohrc_controller.cpp.
Referenced by initController().
resetService()
void OhrcController::resetService (const std::shared_ptr< std_srvs::srv::SetBool::Request > req, const std::shared_ptr< std_srvs::srv::SetBool::Response > & res) private
Definition at line 221 of file ohrc_controller.cpp.
References cartControllers, and isControllerInitialized.
Referenced by initMenbers().
runLoopEnd()
virtual void OhrcController::runLoopEnd () inline private virtual
Definition at line 89 of file ohrc_controller.hpp.
selectInterface()
void OhrcController::selectInterface (std::vector< bool > isEnable) private
Definition at line 144 of file ohrc_controller.cpp.
References _isEnable.
setHightLowPriority()
void OhrcController::setHightLowPriority (int high, int low) private
Definition at line 282 of file ohrc_controller.cpp.
References multimyik_solver_ptr.
setLowPriority()
void OhrcController::setLowPriority (int i) private
Definition at line 252 of file ohrc_controller.cpp.
References multimyik_solver_ptr.
setPriority() [1/3]
void OhrcController::setPriority (int i) private
Definition at line 247 of file ohrc_controller.cpp.
References multimyik_solver_ptr.
setPriority() [2/3]
void OhrcController::setPriority (PriorityType priority) private
Definition at line 270 of file ohrc_controller.cpp.
References autoInd, Automation, manualInd, multimyik_solver_ptr, and priority.
Referenced by initMenbers().
setPriority() [3/3]
void OhrcController::setPriority (std::vector< int > idx) private
Definition at line 260 of file ohrc_controller.cpp.
References multimyik_solver_ptr.
starting()
void OhrcController::starting () private virtual
Definition at line 288 of file ohrc_controller.cpp.
References cartControllers.
Referenced by controlLoop().
stopping()
void OhrcController::stopping () private
Definition at line 313 of file ohrc_controller.cpp.
References cartControllers.
Referenced by ~OhrcController().
update()
void OhrcController::update (const rclcpp::Time & time, const rclcpp::Duration & period) private
Definition at line 334 of file ohrc_controller.cpp.
References cartControllers, math_utility::concatenateVecOfVec(), controller, dt, feedback(), freq, interfaces, multimyik_solver_ptr, nRobot, prev_time, and unique_state.
Referenced by controlLoop().
updateAllCurState()
void OhrcController::updateAllCurState () private
Definition at line 199 of file ohrc_controller.cpp.
References cartControllers.
Referenced by controlLoop(), initController(), and initRobotPose().
updateDesired()
void OhrcController::updateDesired () private
Definition at line 418 of file ohrc_controller.cpp.
References cartControllers, interfaces, nRobot, overrideDesired(), prev_desPose, updateTargetPoseBase(), and updateTargetPoseInterface().
Referenced by controlLoop().
updateTargetPoseBase()
void OhrcController::updateTargetPoseBase (KDL::Frame & pose, KDL::Twist & twist, Interfaces & interfaces_) private
Definition at line 189 of file ohrc_controller.cpp.
References Interfaces::interfaceIdx, Interfaces::interfaces, nRobot, and Interfaces::prev_baseControllerIdx.
Referenced by updateDesired().
updateTargetPoseInterface()
void OhrcController::updateTargetPoseInterface (KDL::Frame & pose, KDL::Twist & twist, Interfaces & interfaces_, KDL::Frame & prev_pose) private
Definition at line 149 of file ohrc_controller.cpp.
References Interfaces::interfaceIdx, Interfaces::interfaces, Interfaces::isEnables, Interfaces::started, and Interfaces::updateIsEnables().
Referenced by updateDesired().
Member Data Documentation
_isEnable
std::vector<bool> OhrcController::_isEnable private
Definition at line 100 of file ohrc_controller.hpp.
Referenced by initInterface(), and selectInterface().
adaptation
bool OhrcController::adaptation = false private
Definition at line 77 of file ohrc_controller.hpp.
adaptationOption_
std::string OhrcController::adaptationOption_ private
Definition at line 85 of file ohrc_controller.hpp.
autoInd
std::vector<int> OhrcController::autoInd private
Definition at line 72 of file ohrc_controller.hpp.
Referenced by initMenbers(), and setPriority().
cartControllers
std::vector<std::shared_ptr<CartController> > OhrcController::cartControllers protected
Definition at line 128 of file ohrc_controller.hpp.
Referenced by controlLoop(), SingleInterface< T >::defineInterface(), MultiInterface::defineInterface(), initController(), initMenbers(), initRobotPose(), publishState(), resetService(), starting(), stopping(), update(), updateAllCurState(), and updateDesired().
control_timer
rclcpp::TimerBase::SharedPtr OhrcController::control_timer private
Definition at line 29 of file ohrc_controller.hpp.
Referenced by initMenbers().
controller
ControllerType OhrcController::controller private
Definition at line 69 of file ohrc_controller.hpp.
Referenced by getRosParams(), initMenbers(), and update().
date
std::string OhrcController::date private
Definition at line 64 of file ohrc_controller.hpp.
dt
double OhrcController::dt private
Definition at line 62 of file ohrc_controller.hpp.
Referenced by controlLoop(), initMenbers(), and update().
exec
rclcpp::executors::MultiThreadedExecutor OhrcController::exec private
Definition at line 21 of file ohrc_controller.hpp.
Referenced by control(), getExecutor(), and initMenbers().
freq
double OhrcController::freq = 500.0 private
Definition at line 61 of file ohrc_controller.hpp.
Referenced by getRosParams(), initMenbers(), and update().
IKmode
enum OhrcController::IKMode OhrcController::IKmode private
Referenced by controlLoop(), and getRosParams().
interfaces
std::vector<Interfaces> OhrcController::interfaces protected
Definition at line 127 of file ohrc_controller.hpp.
Referenced by SingleInterface< T >::defineInterface(), MultiInterface::defineInterface(), initController(), initMenbers(), update(), and updateDesired().
isControllerInitialized
bool OhrcController::isControllerInitialized = false private
Definition at line 25 of file ohrc_controller.hpp.
Referenced by controlLoop(), and resetService().
isStarted
bool OhrcController::isStarted = false private
Definition at line 25 of file ohrc_controller.hpp.
Referenced by controlLoop().
manualInd
std::vector<int> OhrcController::manualInd private
Definition at line 72 of file ohrc_controller.hpp.
Referenced by initMenbers(), and setPriority().
MFmode
enum OhrcController::MFMode OhrcController::MFmode private
Referenced by getRosParams().
multimyik_solver_ptr
std::unique_ptr<MyIK::MyIK> OhrcController::multimyik_solver_ptr private
Definition at line 67 of file ohrc_controller.hpp.
Referenced by initController(), initMenbers(), setHightLowPriority(), setLowPriority(), setPriority(), and update().
myik_ptr
std::vector<std::shared_ptr<MyIK::MyIK> > OhrcController::myik_ptr private
Definition at line 27 of file ohrc_controller.hpp.
Referenced by initMenbers().
node
rclcpp::Node::SharedPtr OhrcController::node private
Definition at line 23 of file ohrc_controller.hpp.
Referenced by control(), getRosParams(), and initMenbers().
nodes
std::vector<rclcpp::Node::SharedPtr> OhrcController::nodes private
Definition at line 22 of file ohrc_controller.hpp.
Referenced by initMenbers().
nRobot
int OhrcController::nRobot = 0 private
Definition at line 57 of file ohrc_controller.hpp.
Referenced by controlLoop(), getNRobot(), initController(), initMenbers(), initRobotPose(), publishState(), update(), updateDesired(), and updateTargetPoseBase().
options
rclcpp::SubscriptionOptions OhrcController::options protected
Definition at line 119 of file ohrc_controller.hpp.
Referenced by initMenbers().
prev_desPose
std::vector<KDL::Frame> OhrcController::prev_desPose private
Definition at line 116 of file ohrc_controller.hpp.
Referenced by initMenbers(), and updateDesired().
prev_time
std::vector<rclcpp::Time> OhrcController::prev_time private
Definition at line 74 of file ohrc_controller.hpp.
Referenced by initMenbers(), and update().
priority
enum OhrcController::PriorityType OhrcController::priority private
Referenced by getRosParams(), initMenbers(), and setPriority().
priorityIdx
int OhrcController::priorityIdx = 0 protected
Definition at line 125 of file ohrc_controller.hpp.
Referenced by priorityService().
priorityServer
rclcpp::Service<ohrc_msgs::srv::SetPriority>::SharedPtr OhrcController::priorityServer private
Definition at line 36 of file ohrc_controller.hpp.
Referenced by initMenbers().
publisher
PublisherType OhrcController::publisher private
Definition at line 70 of file ohrc_controller.hpp.
resetServer
rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr OhrcController::resetServer private
Definition at line 35 of file ohrc_controller.hpp.
Referenced by initMenbers().
root_frame
std::string OhrcController::root_frame private
Definition at line 60 of file ohrc_controller.hpp.
Referenced by getRosParams(), and initMenbers().
t0
rclcpp::Time OhrcController::t0 private
Definition at line 63 of file ohrc_controller.hpp.
Referenced by initController().
unique_state
bool OhrcController::unique_state = false private
Definition at line 58 of file ohrc_controller.hpp.
Referenced by getRosParams(), initMenbers(), initRobotPose(), and update().
The documentation for this class was generated from the following files:
ohrc_controller.hpp
ohrc_controller.cpp