OpenHRC: OmegaInterface Class Reference
OmegaInterface Class Reference
#include <omega_interface.hpp>
Public Member Functions
void initInterface () override
StateTopicInterface (const std::shared_ptr< CartController > &controller)
Public Member Functions inherited from StateTopicInterface
StateTopicInterface (const std::shared_ptr< CartController > &controller)
void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Protected Types
enum HapticType { PositionPositionFeedback , PositionForce , PositionForceFeedback , None }
Protected Member Functions
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist) override
virtual void modifyTargetState (ohrc_msgs::State &state) override
Protected Member Functions inherited from StateTopicInterface
void cbState (const ohrc_msgs::msg::State::SharedPtr msg)
virtual void modifyTargetState (ohrc_msgs::msg::State &state)
virtual void setSubscriber ()
void getTargetState (const ohrc_msgs::msg::State &state, KDL::Frame &pos, KDL::Twist &twist)
void resetInterface () override
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes
ros::Publisher pubOmegaPose
ros::Publisher pubOmegaForce
ros::Publisher pubEnergy
ros::Publisher pubOmegaForceVis
enum OmegaInterface::HapticType hapticType
VectorXd ft_omega
Protected Attributes inherited from StateTopicInterface
rclcpp::Subscription< ohrc_msgs::msg::State >::SharedPtr subState
Affine3d T_state_base
double k_trans = 1.0
Affine3d T
Affine3d T_start
Affine3d T_state_start
bool isFirst = true
ohrc_msgs::msg::State _state
bool _flagTopic = false
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 8 of file omega_interface.hpp.
Member Enumeration Documentation
HapticType
enum OmegaInterface::HapticType protected
Enumerator
PositionPositionFeedback
PositionForce
PositionForceFeedback
None
Definition at line 14 of file omega_interface.hpp.
Member Function Documentation
feedback()
void OmegaInterface::feedback (const KDL::Frame & targetPos, const KDL::Twist & targetTwist) override protected virtual
Reimplemented from Interface.
Definition at line 28 of file omega_interface.cpp.
References Interface::controller, tf2::fromMsg(), ft_omega, hapticType, PositionForce, PositionForceFeedback, PositionPositionFeedback, pubOmegaForce, pubOmegaForceVis, StateTopicInterface::T_state_base, and tf2::toMsg().
initInterface()
void OmegaInterface::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file omega_interface.cpp.
References Interface::controller, hapticType, StateTopicInterface::initInterface(), None, pubOmegaForce, pubOmegaForceVis, Interface::stateFrameId, and Interface::stateTopicName.
modifyTargetState()
void OmegaInterface::modifyTargetState (ohrc_msgs::State & state) override protected virtual
Definition at line 22 of file omega_interface.cpp.
References tf2::fromMsg(), and ft_omega.
StateTopicInterface()
StateTopicInterface::StateTopicInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 28 of file state_topic_interface.hpp.
Member Data Documentation
ft_omega
VectorXd OmegaInterface::ft_omega protected
Definition at line 18 of file omega_interface.hpp.
Referenced by feedback(), and modifyTargetState().
hapticType
enum OmegaInterface::HapticType OmegaInterface::hapticType protected
Referenced by feedback(), and initInterface().
pubEnergy
ros::Publisher OmegaInterface::pubEnergy protected
Definition at line 12 of file omega_interface.hpp.
pubOmegaForce
ros::Publisher OmegaInterface::pubOmegaForce protected
Definition at line 12 of file omega_interface.hpp.
Referenced by feedback(), and initInterface().
pubOmegaForceVis
ros::Publisher OmegaInterface::pubOmegaForceVis protected
Definition at line 12 of file omega_interface.hpp.
Referenced by feedback(), and initInterface().
pubOmegaPose
ros::Publisher OmegaInterface::pubOmegaPose protected
Definition at line 12 of file omega_interface.hpp.
The documentation for this class was generated from the following files:
omega_interface.hpp
omega_interface.cpp