OpenHRC: XrBodyInterface Class Reference
XrBodyInterface Class Reference
#include <xr_body_interface.hpp>
Public Member Functions
XrBodyInterface (const std::shared_ptr< CartController > &controller)
void initInterface () override
void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
StateTopicInterface (const std::shared_ptr< CartController > &controller)
Public Member Functions inherited from StateTopicInterface
StateTopicInterface (const std::shared_ptr< CartController > &controller)
void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Protected Member Functions
virtual bool getEnableFlag (const ohrc_msgs::msg::BodyPartState &handState, const ohrc_msgs::msg::BodyPartState &anotherBodyPartState)
Protected Member Functions inherited from StateTopicInterface
void cbState (const ohrc_msgs::msg::State::SharedPtr msg)
virtual void modifyTargetState (ohrc_msgs::msg::State &state)
virtual void setSubscriber ()
void getTargetState (const ohrc_msgs::msg::State &state, KDL::Frame &pos, KDL::Twist &twist)
void resetInterface () override
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Private Types
enum class BodyPart {
RIGHT_HAND , LEFT_HAND , HEAD , EITHER_HANDS ,
None
}
enum class Hand { RIGHT , LEFT }
Private Member Functions
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist) override
void cbBody (const ohrc_msgs::msg::BodyState::SharedPtr msg)
void setSubscriber () override
Private Attributes
rclcpp::Subscription< ohrc_msgs::msg::BodyState >::SharedPtr subBody
rclcpp::Publisher< std_msgs::msg::Float32 >::SharedPtr pubFeedback
ohrc_msgs::msg::State _state
ohrc_msgs::msg::BodyState _body
enum XrBodyInterface::BodyPart bodyPart
enum XrBodyInterface::Hand hand
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Protected Attributes inherited from StateTopicInterface
rclcpp::Subscription< ohrc_msgs::msg::State >::SharedPtr subState
Affine3d T_state_base
double k_trans = 1.0
Affine3d T
Affine3d T_start
Affine3d T_state_start
bool isFirst = true
ohrc_msgs::msg::State _state
bool _flagTopic = false
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Detailed Description
Definition at line 9 of file xr_body_interface.hpp.
Member Enumeration Documentation
BodyPart
enum class XrBodyInterface::BodyPart strong private
Enumerator
RIGHT_HAND
LEFT_HAND
HEAD
EITHER_HANDS
None
Definition at line 18 of file xr_body_interface.hpp.
Hand
enum class XrBodyInterface::Hand strong private
Enumerator
RIGHT
LEFT
Definition at line 19 of file xr_body_interface.hpp.
Constructor & Destructor Documentation
XrBodyInterface()
XrBodyInterface::XrBodyInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 29 of file xr_body_interface.hpp.
Member Function Documentation
cbBody()
void XrBodyInterface::cbBody (const ohrc_msgs::msg::BodyState::SharedPtr msg) private
Definition at line 22 of file xr_body_interface.cpp.
References StateTopicInterface::_flagTopic, _state, bodyPart, EITHER_HANDS, getEnableFlag(), hand, HEAD, Interface::isEnable, LEFT, LEFT_HAND, Interface::mtx, Interface::reset(), RIGHT, and RIGHT_HAND.
Referenced by setSubscriber().
feedback()
void XrBodyInterface::feedback (const KDL::Frame & targetPos, const KDL::Twist & targetTwist) override private virtual
Reimplemented from Interface.
Definition at line 114 of file xr_body_interface.cpp.
References Interface::controller, and tf2::fromMsg().
getEnableFlag()
bool XrBodyInterface::getEnableFlag (const ohrc_msgs::msg::BodyPartState & handState, const ohrc_msgs::msg::BodyPartState & anotherBodyPartState) protected virtual
Definition at line 89 of file xr_body_interface.cpp.
Referenced by cbBody().
initInterface()
void XrBodyInterface::initInterface () override virtual
Reimplemented from StateTopicInterface.
Definition at line 3 of file xr_body_interface.cpp.
References bodyPart, Interface::controller, RclcppUtility::declare_and_get_parameter_enum(), Interface::node, pubFeedback, RIGHT_HAND, Interface::robot_ns, setSubscriber(), Interface::stateFrameId, and StateTopicInterface::T_state_base.
setSubscriber()
void XrBodyInterface::setSubscriber () override private virtual
Reimplemented from StateTopicInterface.
Definition at line 16 of file xr_body_interface.cpp.
References cbBody(), Interface::getTopicAndFrameName(), Interface::node, Interface::stateTopicName, and subBody.
Referenced by initInterface().
StateTopicInterface()
StateTopicInterface::StateTopicInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 28 of file state_topic_interface.hpp.
updateTargetPose()
void XrBodyInterface::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from StateTopicInterface.
Definition at line 96 of file xr_body_interface.cpp.
References StateTopicInterface::_flagTopic, _state, StateTopicInterface::getTargetState(), and Interface::mtx.
Member Data Documentation
_body
ohrc_msgs::msg::BodyState XrBodyInterface::_body private
Definition at line 17 of file xr_body_interface.hpp.
_state
ohrc_msgs::msg::State XrBodyInterface::_state private
Definition at line 15 of file xr_body_interface.hpp.
Referenced by cbBody(), and updateTargetPose().
bodyPart
enum XrBodyInterface::BodyPart XrBodyInterface::bodyPart private
Referenced by cbBody(), and initInterface().
hand
enum XrBodyInterface::Hand XrBodyInterface::hand private
Referenced by cbBody().
pubFeedback
rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr XrBodyInterface::pubFeedback private
Definition at line 11 of file xr_body_interface.hpp.
Referenced by initInterface().
subBody
rclcpp::Subscription<ohrc_msgs::msg::BodyState>::SharedPtr XrBodyInterface::subBody private
Definition at line 10 of file xr_body_interface.hpp.
Referenced by setSubscriber().
The documentation for this class was generated from the following files:
xr_body_interface.hpp
xr_body_interface.cpp