OpenHRC: PoseTopicInterface Class Reference
PoseTopicInterface Class Reference
#include <pose_topic_interface.hpp>
Public Member Functions
PoseTopicInterface (const std::shared_ptr< CartController > &controller)
void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist) override
void initInterface () override
void resetInterface () override
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
Public Member Functions inherited from Interface
Interface (const std::shared_ptr< CartController > &controller)
Interface (const std::shared_ptr< CartController > &controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode)
~Interface ()
virtual void updateTargetPose (const rclcpp::Time t, KDL::Frame &pose, KDL::Twist &twist)
virtual void initInterface ()
virtual void resetInterface ()
virtual void updateInterface ()
virtual void feedback (const KDL::Frame &targetPos, const KDL::Twist &targetTwist)
std::string getTargetName ()
double getTargetDistance ()
TaskState getTaskState ()
VectorXd getTargetError ()
bool getIsEnable ()
void setIsEnable (bool isEnable)
FeedbackMode getFeedbackMode ()
Protected Member Functions
void cbPose (const geometry_msgs::msg::Pose::SharedPtr msg)
virtual void setSubscriber ()
void setPoseFromTwistMsg (const geometry_msgs::msg::Twist &twist_msg, KDL::Frame &pos, KDL::Twist &twist)
Protected Member Functions inherited from Interface
void reset ()
void getTopicAndFrameName (std::string DefaultStateTopicName, std::string DefaultStateFrameId)
bool updateIsEnable (bool condition)
Protected Attributes
bool _flagTopic = false
Affine3d T
Matrix3d R
bool isFirst = true
ohrc_msgs::msg::State state
KDL::Frame prevPoses
Protected Attributes inherited from Interface
const double dt
const std::string robot_ns
const std::shared_ptr< CartController > controller
const rclcpp::Node::SharedPtr node
TaskState taskState = TaskState::Initial
std::string targetName
double targetDistance = 0.0
VectorXd e
std::string stateTopicName = "/state"
std::string stateFrameId = "world"
bool isEnable = false
const std::string interfaceName = ""
bool interfaceRunning = false
FeedbackMode feedbackMode
Private Attributes
rclcpp::Subscription< geometry_msgs::msg::Pose >::SharedPtr subPose
geometry_msgs::msg::Pose _pose
double k_trans = 1.0
Additional Inherited Members
Public Attributes inherited from Interface
std::mutex mtx
int targetIdx = -1
int nCompletedTask = 0
bool blocked = false
Detailed Description
Definition at line 9 of file pose_topic_interface.hpp.
Constructor & Destructor Documentation
PoseTopicInterface()
PoseTopicInterface::PoseTopicInterface (const std::shared_ptr< CartController > & controller) inline
Definition at line 32 of file pose_topic_interface.hpp.
Member Function Documentation
cbPose()
void PoseTopicInterface::cbPose (const geometry_msgs::msg::Pose::SharedPtr msg) protected
Definition at line 23 of file pose_topic_interface.cpp.
References _flagTopic, _pose, Interface::mtx, and Interface::updateIsEnable().
Referenced by setSubscriber().
initInterface()
void PoseTopicInterface::initInterface () override virtual
Reimplemented from Interface.
Definition at line 3 of file pose_topic_interface.cpp.
References Interface::controller, RclcppUtility::declare_and_get_parameter(), Interface::node, R, setSubscriber(), and Interface::stateFrameId.
Interface() [1/2]
Interface::Interface (const std::shared_ptr< CartController > & controller) inline
Definition at line 57 of file interface.hpp.
Interface() [2/2]
Interface::Interface (const std::shared_ptr< CartController > & controller, const std::string interfaceName, FeedbackMode defaultFeedbackMode) inline
Definition at line 60 of file interface.hpp.
resetInterface()
void PoseTopicInterface::resetInterface () override virtual
Reimplemented from Interface.
Definition at line 53 of file pose_topic_interface.cpp.
References _flagTopic.
setPoseFromTwistMsg()
void PoseTopicInterface::setPoseFromTwistMsg (const geometry_msgs::msg::Twist & twist_msg, KDL::Frame & pos, KDL::Twist & twist) protected
setSubscriber()
void PoseTopicInterface::setSubscriber () protected virtual
Definition at line 16 of file pose_topic_interface.cpp.
References cbPose(), Interface::controller, Interface::getTopicAndFrameName(), Interface::node, Interface::stateTopicName, and subPose.
Referenced by initInterface().
updateTargetPose()
void PoseTopicInterface::updateTargetPose (const rclcpp::Time t, KDL::Frame & pose, KDL::Twist & twist) override virtual
Reimplemented from Interface.
Definition at line 31 of file pose_topic_interface.cpp.
References _flagTopic, _pose, Interface::controller, tf2::fromMsg(), Interface::mtx, and R.
Member Data Documentation
_flagTopic
bool PoseTopicInterface::_flagTopic = false protected
Definition at line 16 of file pose_topic_interface.hpp.
Referenced by cbPose(), resetInterface(), and updateTargetPose().
_pose
geometry_msgs::msg::Pose PoseTopicInterface::_pose private
Definition at line 11 of file pose_topic_interface.hpp.
Referenced by cbPose(), and updateTargetPose().
isFirst
bool PoseTopicInterface::isFirst = true protected
Definition at line 20 of file pose_topic_interface.hpp.
k_trans
double PoseTopicInterface::k_trans = 1.0 private
Definition at line 13 of file pose_topic_interface.hpp.
prevPoses
KDL::Frame PoseTopicInterface::prevPoses protected
Definition at line 23 of file pose_topic_interface.hpp.
R
Matrix3d PoseTopicInterface::R protected
Definition at line 19 of file pose_topic_interface.hpp.
Referenced by initInterface(), and updateTargetPose().
state
ohrc_msgs::msg::State PoseTopicInterface::state protected
Definition at line 22 of file pose_topic_interface.hpp.
subPose
rclcpp::Subscription<geometry_msgs::msg::Pose>::SharedPtr PoseTopicInterface::subPose private
Definition at line 10 of file pose_topic_interface.hpp.
Referenced by setSubscriber().
T
Affine3d PoseTopicInterface::T protected
Definition at line 18 of file pose_topic_interface.hpp.
The documentation for this class was generated from the following files:
pose_topic_interface.hpp
pose_topic_interface.cpp