OpenHRC: subscriber_utility Namespace Reference
subscriber_utility Namespace Reference
Functions
bool checkTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex *mtx, std::string name)
bool checkSubTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex *mtx)
bool checkSubTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex *mtx, std::string robot_ns)
bool checkSubTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex *mtx, std::string name, std::string robot_ns)
Function Documentation
checkSubTopic() [1/3]
bool subscriber_utility::checkSubTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex * mtx) inline
Definition at line 44 of file subscriber_utility.h.
References checkTopic().
Referenced by ForwardingController::control(), and CartController::starting().
checkSubTopic() [2/3]
bool subscriber_utility::checkSubTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex * mtx, std::string name, std::string robot_ns) inline
Definition at line 52 of file subscriber_utility.h.
References checkTopic().
checkSubTopic() [3/3]
bool subscriber_utility::checkSubTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex * mtx, std::string robot_ns) inline
Definition at line 48 of file subscriber_utility.h.
References checkTopic().
checkTopic()
bool subscriber_utility::checkTopic (rclcpp::Node::SharedPtr node, std::vector< bool * > VecSubFlagPtr, std::mutex * mtx, std::string name) inline
Definition at line 11 of file subscriber_utility.h.
Referenced by checkSubTopic().