OpenHRC: RclcppUtility Namespace Reference
RclcppUtility Namespace Reference
Functions
template<typename T >
T print (const T &value)
template<typename T >
std::string print (const std::vector< T > &vec)
template<typename T >
bool declare_and_get_parameter (const rclcpp::Node::SharedPtr &node, std::string param_name, T default_value, T &param_value, bool verbose=true)
template<typename T >
bool declare_and_get_parameter_enum (const rclcpp::Node::SharedPtr &node, std::string param_name, T default_enum, T &param_enum, bool verbose=true)
Function Documentation
declare_and_get_parameter()
template<typename T > bool RclcppUtility::declare_and_get_parameter (const rclcpp::Node::SharedPtr & node, std::string param_name, T default_value, T & param_value, bool verbose = true) inline
Definition at line 35 of file rclcpp_utility.hpp.
References print().
Referenced by declare_and_get_parameter_enum(), AdmittanceController::getImpCoeff(), CartController::getRosParams(), OhrcController::getRosParams(), Interface::getTopicAndFrameName(), ModelUtility::getURDFModel(), JoyTopicInterface::initInterface(), PoseTopicInterface::initInterface(), StateTopicInterface::initInterface(), TwistTopicInterface::initInterface(), MyIK::MyIK::MyIK(), and JoyTopicInterface::setSubscriber().
declare_and_get_parameter_enum()
template<typename T > bool RclcppUtility::declare_and_get_parameter_enum (const rclcpp::Node::SharedPtr & node, std::string param_name, T default_enum, T & param_enum, bool verbose = true) inline
Definition at line 48 of file rclcpp_utility.hpp.
References declare_and_get_parameter(), and print().
Referenced by CartController::getRosParams(), OhrcController::getRosParams(), DummyInterface::initInterface(), XrBodyInterface::initInterface(), Interface::Interface(), and JoyTopicInterface::setSubscriber().
print() [1/2]
template<typename T > std::string RclcppUtility::print (const std::vector< T > & vec)
Definition at line 20 of file rclcpp_utility.hpp.
print() [2/2]
template<typename T > T RclcppUtility::print (const T & value)
Definition at line 15 of file rclcpp_utility.hpp.
Referenced by declare_and_get_parameter(), and declare_and_get_parameter_enum().