OpenHRC: rotation_util Namespace Reference
rotation_util Namespace Reference
Functions
bool checkQuaternionSign (Eigen::Quaterniond q)
checkQuaternionSign
Eigen::Quaterniond flipQuaterionSign (Eigen::Quaterniond q)
flipQuaterionSign
Eigen::Quaterniond checkFlipQuaternionSign (Eigen::Quaterniond q)
checkFlipQuaternionSign
void getQuaternionError (const Eigen::Quaterniond &desired_q, const Eigen::Quaterniond &current_q, Eigen::Quaterniond &error_q)
Eigen::Vector3d getQuaternionLogError (const Eigen::Quaterniond &desired_q, const Eigen::Quaterniond &current_q)
Eigen::Vector3d getQuaternionError (const Eigen::Quaterniond &desired_q, const Eigen::Quaterniond &current_q)
getQuaternionError
double getQuaternionErrorYaw (const double &yaw1, const double &yaw2)
Eigen::Vector3d getErrorEuler (const Eigen::Matrix3d &desired_R, const Eigen::Matrix3d &current_R)
Eigen::Vector3d getErrorEuler (const Eigen::Quaterniond &desired_q, const Eigen::Quaterniond &current_q)
Eigen::Vector3d getRotationMatrixError (const Eigen::Matrix3d &desired_R, const Eigen::Matrix3d &current_R)
Function Documentation
checkFlipQuaternionSign()
Eigen::Quaterniond rotation_util::checkFlipQuaternionSign (Eigen::Quaterniond q) inline
checkFlipQuaternionSign
Parameters
q
Returns
Definition at line 37 of file coordination_utility.h.
References checkQuaternionSign(), and flipQuaterionSign().
Referenced by getQuaternionError().
checkQuaternionSign()
bool rotation_util::checkQuaternionSign (Eigen::Quaterniond q) inline
checkQuaternionSign
Parameters
q
Returns
Definition at line 16 of file coordination_utility.h.
Referenced by checkFlipQuaternionSign().
flipQuaterionSign()
Eigen::Quaterniond rotation_util::flipQuaterionSign (Eigen::Quaterniond q) inline
flipQuaterionSign
Parameters
q
Returns
Definition at line 28 of file coordination_utility.h.
Referenced by checkFlipQuaternionSign().
getErrorEuler() [1/2]
Eigen::Vector3d rotation_util::getErrorEuler (const Eigen::Matrix3d & desired_R, const Eigen::Matrix3d & current_R) inline
Definition at line 97 of file coordination_utility.h.
getErrorEuler() [2/2]
Eigen::Vector3d rotation_util::getErrorEuler (const Eigen::Quaterniond & desired_q, const Eigen::Quaterniond & current_q) inline
Definition at line 101 of file coordination_utility.h.
References getQuaternionError().
getQuaternionError() [1/2]
Eigen::Vector3d rotation_util::getQuaternionError (const Eigen::Quaterniond & desired_q, const Eigen::Quaterniond & current_q) inline
getQuaternionError
Parameters
desired_q
current_q
Returns
Definition at line 76 of file coordination_utility.h.
References getQuaternionError().
getQuaternionError() [2/2]
void rotation_util::getQuaternionError (const Eigen::Quaterniond & desired_q, const Eigen::Quaterniond & current_q, Eigen::Quaterniond & error_q) inline
Definition at line 44 of file coordination_utility.h.
References checkFlipQuaternionSign().
Referenced by getErrorEuler(), getQuaternionError(), getQuaternionErrorYaw(), getQuaternionLogError(), and CartController::getVelocity().
getQuaternionErrorYaw()
double rotation_util::getQuaternionErrorYaw (const double & yaw1, const double & yaw2) inline
Definition at line 85 of file coordination_utility.h.
References getQuaternionError(), and tf2::toMsg().
getQuaternionLogError()
Eigen::Vector3d rotation_util::getQuaternionLogError (const Eigen::Quaterniond & desired_q, const Eigen::Quaterniond & current_q) inline
Definition at line 55 of file coordination_utility.h.
References getQuaternionError().
getRotationMatrixError()
Eigen::Vector3d rotation_util::getRotationMatrixError (const Eigen::Matrix3d & desired_R, const Eigen::Matrix3d & current_R) inline
Definition at line 110 of file coordination_utility.h.
Referenced by MyIK::MyIK::CartToJntVel_qp_manipOpt(), and MyIK::getCartError().