OpenHRC: math_utility Namespace Reference
math_utility Namespace Reference
Classes
class Integrator
Functions
double sigmoid (double x, double a, double x0, double y0, double k)
double sigmoid (double x, double gain)
double sigmoid (double x)
bool inConvex (Eigen::Vector2d p, std::vector< Eigen::Vector2d > apexes)
template<class T >
T clamp (T value, T min, T max)
template<class T >
T deadZone (T value, T upper, T lower)
template<class T >
T deadZone (T value, T upper)
template<typename T >
Eigen::Matrix< T, 3, 3 > skew (const Eigen::Matrix< T, 3, 1 > &vec)
Eigen::VectorXd concatenateVecOfVec (std::vector< Eigen::VectorXd > vecOfVec)
Eigen::VectorXd concatenateVecOfVec (std::vector< KDL::JntArray > vecOfVec)
std::vector< Eigen::VectorXd > splitVec (Eigen::VectorXd vec, std::vector< int > num)
std::vector< Eigen::VectorXd > splitVec (Eigen::VectorXd vec, std::vector< Eigen::VectorXd > &vecOfVec)
template<typename T >
T sgn (T val)
Eigen::Quaterniond QuatFromTwoVectors (Eigen::Vector3d u, Eigen::Vector3d v)
Eigen::MatrixXd numericalMatrixDifferntiation (Eigen::MatrixXd A_plus, Eigen::MatrixXd A_minus, double delta)
Function Documentation
clamp()
template<class T > T math_utility::clamp (T value, T min, T max)
Definition at line 51 of file math_utility.h.
Referenced by geometry_msgs_utility::clamp().
concatenateVecOfVec() [1/2]
Eigen::VectorXd math_utility::concatenateVecOfVec (std::vector< Eigen::VectorXd > vecOfVec) inline
Definition at line 77 of file math_utility.h.
Referenced by OhrcController::initRobotPose(), and OhrcController::update().
concatenateVecOfVec() [2/2]
Eigen::VectorXd math_utility::concatenateVecOfVec (std::vector< KDL::JntArray > vecOfVec) inline
Definition at line 93 of file math_utility.h.
deadZone() [1/2]
template<class T > T math_utility::deadZone (T value, T upper)
Definition at line 66 of file math_utility.h.
References deadZone().
deadZone() [2/2]
template<class T > T math_utility::deadZone (T value, T upper, T lower)
Definition at line 57 of file math_utility.h.
Referenced by geometry_msgs_utility::deadZone(), and deadZone().
inConvex()
bool math_utility::inConvex (Eigen::Vector2d p, std::vector< Eigen::Vector2d > apexes) inline
Definition at line 27 of file math_utility.h.
numericalMatrixDifferntiation()
Eigen::MatrixXd math_utility::numericalMatrixDifferntiation (Eigen::MatrixXd A_plus, Eigen::MatrixXd A_minus, double delta) inline
Definition at line 143 of file math_utility.h.
Referenced by MyIK::MyIK::getDeltaManipulability().
QuatFromTwoVectors()
Eigen::Quaterniond math_utility::QuatFromTwoVectors (Eigen::Vector3d u, Eigen::Vector3d v) inline
Definition at line 136 of file math_utility.h.
sgn()
template<typename T > T math_utility::sgn (T val)
Definition at line 131 of file math_utility.h.
Referenced by TEST().
sigmoid() [1/3]
double math_utility::sigmoid (double x) inline
Definition at line 22 of file math_utility.h.
References sigmoid().
sigmoid() [2/3]
double math_utility::sigmoid (double x, double a, double x0, double y0, double k) inline
Definition at line 14 of file math_utility.h.
Referenced by sigmoid().
sigmoid() [3/3]
double math_utility::sigmoid (double x, double gain) inline
Definition at line 18 of file math_utility.h.
References sigmoid().
skew()
template<typename T > Eigen::Matrix< T, 3, 3 > math_utility::skew (const Eigen::Matrix< T, 3, 1 > & vec)
Definition at line 72 of file math_utility.h.
splitVec() [1/2]
std::vector< Eigen::VectorXd > math_utility::splitVec (Eigen::VectorXd vec, std::vector< Eigen::VectorXd > & vecOfVec) inline
Definition at line 120 of file math_utility.h.
References splitVec().
splitVec() [2/2]
std::vector< Eigen::VectorXd > math_utility::splitVec (Eigen::VectorXd vec, std::vector< int > num) inline
Definition at line 109 of file math_utility.h.
Referenced by splitVec().