OpenHRC: geometry_msgs_utility Namespace Reference
geometry_msgs_utility Namespace Reference
Classes
struct paramDeadZone
class Point
class Vector3
class Wrench
class WrenchStamped
Functions
double dist (geometry_msgs::msg::Point point1, geometry_msgs::msg::Point point2)
void initPoint (geometry_msgs::msg::Point &point, double x, double y, double z)
void initPoint (geometry_msgs::msg::Point &point, double val)
void clamp (geometry_msgs::msg::Point &point, double x_max, double y_max, double z_max, double x_min, double y_min, double z_min)
void clamp (geometry_msgs::msg::Point &point, double max, double min)
void clamp_moreThan (geometry_msgs::msg::Point &point, double x, double y, double z)
void clamp_moreThan (geometry_msgs::msg::Point &point, double val)
void clamp_lessThan (geometry_msgs::msg::Point &point, double x, double y, double z)
void clamp_lessThan (geometry_msgs::msg::Point &point, double val)
geometry_msgs::msg::Point error (geometry_msgs::msg::Point point1, geometry_msgs::msg::Point point2)
geometry_msgs::msg::Point sum (std::vector< geometry_msgs::msg::Point > points)
geometry_msgs::msg::Point average (std::vector< geometry_msgs::msg::Point > points)
geometry_msgs::msg::Twist checkNanInf (geometry_msgs::msg::Twist cmd)
geometry_msgs::msg::Twist cropMinMax (geometry_msgs::msg::Twist cmd, geometry_msgs::msg::Twist min, geometry_msgs::msg::Twist max)
Eigen::VectorXd toVector (geometry_msgs::msg::Twist twist, Eigen::VectorXd &vector)
Eigen::VectorXd toVector (geometry_msgs::msg::Twist twist)
geometry_msgs::msg::Twist fromVector (Eigen::VectorXd vector, geometry_msgs::msg::Twist &twist)
void deadZone (geometry_msgs::msg::Wrench raw_wrench, geometry_msgs::msg::Wrench &filtered_wrench, paramDeadZone param)
geometry_msgs::msg::Wrench transformFT (geometry_msgs::msg::Wrench ft_in, const Affine3d trans)
void deadZone (geometry_msgs::msg::WrenchStamped wrenchStamped, geometry_msgs::msg::WrenchStamped &filtered_wrenchStamped, paramDeadZone param)
Function Documentation
average()
geometry_msgs::msg::Point geometry_msgs_utility::average (std::vector< geometry_msgs::msg::Point > points)
Definition at line 121 of file Point.cpp.
References sum().
checkNanInf()
geometry_msgs::msg::Twist geometry_msgs_utility::checkNanInf (geometry_msgs::msg::Twist cmd)
Definition at line 11 of file Twist.cpp.
References error().
clamp() [1/2]
void geometry_msgs_utility::clamp (geometry_msgs::msg::Point & point, double max, double min)
Definition at line 68 of file Point.cpp.
References clamp().
clamp() [2/2]
void geometry_msgs_utility::clamp (geometry_msgs::msg::Point & point, double x_max, double y_max, double z_max, double x_min, double y_min, double z_min)
Definition at line 62 of file Point.cpp.
References math_utility::clamp().
Referenced by clamp().
clamp_lessThan() [1/2]
void geometry_msgs_utility::clamp_lessThan (geometry_msgs::msg::Point & point, double val)
Definition at line 98 of file Point.cpp.
References clamp_lessThan().
clamp_lessThan() [2/2]
void geometry_msgs_utility::clamp_lessThan (geometry_msgs::msg::Point & point, double x, double y, double z)
Definition at line 87 of file Point.cpp.
Referenced by clamp_lessThan().
clamp_moreThan() [1/2]
void geometry_msgs_utility::clamp_moreThan (geometry_msgs::msg::Point & point, double val)
Definition at line 83 of file Point.cpp.
References clamp_moreThan().
clamp_moreThan() [2/2]
void geometry_msgs_utility::clamp_moreThan (geometry_msgs::msg::Point & point, double x, double y, double z)
Definition at line 72 of file Point.cpp.
Referenced by clamp_moreThan().
cropMinMax()
geometry_msgs::msg::Twist geometry_msgs_utility::cropMinMax (geometry_msgs::msg::Twist cmd, geometry_msgs::msg::Twist min, geometry_msgs::msg::Twist max)
Definition at line 33 of file Twist.cpp.
deadZone() [1/2]
void geometry_msgs_utility::deadZone (geometry_msgs::msg::Wrench raw_wrench, geometry_msgs::msg::Wrench & filtered_wrench, paramDeadZone param)
Definition at line 59 of file Wrench.cpp.
References math_utility::deadZone(), geometry_msgs_utility::paramDeadZone::force_lower, geometry_msgs_utility::paramDeadZone::force_upper, geometry_msgs_utility::paramDeadZone::torque_lower, and geometry_msgs_utility::paramDeadZone::torque_upper.
Referenced by deadZone(), and geometry_msgs_utility::Wrench::deadZone_LPF().
deadZone() [2/2]
void geometry_msgs_utility::deadZone (geometry_msgs::msg::WrenchStamped wrenchStamped, geometry_msgs::msg::WrenchStamped & filtered_wrenchStamped, paramDeadZone param)
Definition at line 12 of file WrenchStamped.cpp.
References deadZone().
dist()
double geometry_msgs_utility::dist (geometry_msgs::msg::Point point1, geometry_msgs::msg::Point point2)
Definition at line 49 of file Point.cpp.
error()
geometry_msgs::msg::Point geometry_msgs_utility::error (geometry_msgs::msg::Point point1, geometry_msgs::msg::Point point2)
Definition at line 102 of file Point.cpp.
Referenced by checkNanInf().
fromVector()
geometry_msgs::msg::Twist geometry_msgs_utility::fromVector (Eigen::VectorXd vector, geometry_msgs::msg::Twist & twist) inline
Definition at line 50 of file Twist.h.
initPoint() [1/2]
void geometry_msgs_utility::initPoint (geometry_msgs::msg::Point & point, double val)
Definition at line 58 of file Point.cpp.
References initPoint().
initPoint() [2/2]
void geometry_msgs_utility::initPoint (geometry_msgs::msg::Point & point, double x, double y, double z)
Definition at line 53 of file Point.cpp.
Referenced by initPoint().
sum()
geometry_msgs::msg::Point geometry_msgs_utility::sum (std::vector< geometry_msgs::msg::Point > points)
Definition at line 111 of file Point.cpp.
Referenced by average().
toVector() [1/2]
Eigen::VectorXd geometry_msgs_utility::toVector (geometry_msgs::msg::Twist twist) inline
Definition at line 45 of file Twist.h.
References toVector().
toVector() [2/2]
Eigen::VectorXd geometry_msgs_utility::toVector (geometry_msgs::msg::Twist twist, Eigen::VectorXd & vector) inline
Definition at line 34 of file Twist.h.
Referenced by toVector().
transformFT()
geometry_msgs::msg::Wrench geometry_msgs_utility::transformFT (geometry_msgs::msg::Wrench ft_in, const Affine3d trans) inline
Definition at line 53 of file Wrench.h.
References tf2::fromMsg(), tf2::toMsg(), and TransformUtility::transformFT().
Referenced by CartController::cbForce().