OpenHRC: tf2 Namespace Reference
tf2 Namespace Reference
Functions
Eigen::VectorXd fromMsg (const geometry_msgs::msg::Twist twist, Eigen::VectorXd &vector)
Eigen::VectorXd fromMsg (geometry_msgs::msg::Wrench raw_wrench, Eigen::VectorXd &vector)
Eigen::VectorXd fromMsg (geometry_msgs::msg::Wrench raw_wrench)
geometry_msgs::msg::Wrench toMsg (Eigen::VectorXd vector, geometry_msgs::msg::Wrench &wrench)
void fromMsg (const geometry_msgs::msg::Twist &msg, KDL::Twist &out)
void fromMsg (const geometry_msgs::msg::PoseArray &msg, std::vector< Affine3d > &Ts)
Function Documentation
fromMsg() [1/5]
void tf2::fromMsg (const geometry_msgs::msg::PoseArray & msg, std::vector< Affine3d > & Ts) inline
Definition at line 89 of file transform_utility.h.
References fromMsg().
fromMsg() [2/5]
void tf2::fromMsg (const geometry_msgs::msg::Twist & msg, KDL::Twist & out) inline
Definition at line 80 of file transform_utility.h.
fromMsg() [3/5]
Eigen::VectorXd tf2::fromMsg (const geometry_msgs::msg::Twist twist, Eigen::VectorXd & vector) inline
Definition at line 15 of file Twist.h.
Referenced by ImpedanceController::cbTargetPoses(), CartTrajectoryImpedanceController::cbTargetPoses(), OmegaInterface::feedback(), XrBodyInterface::feedback(), FTFilter::filter_cb(), fromMsg(), CartController::getForceEefVec(), StateTopicInterface::getTargetState(), CartTrajectoryImpedanceController::getTrajectories(), OmegaInterface::modifyTargetState(), TwistTopicInterface::setPoseFromTwistMsg(), geometry_msgs_utility::transformFT(), nav_msgs_utility::Odometry::transFromOdom(), nav_msgs_utility::Odometry::transToOdom(), ImpedanceController::updataTaskState(), CartTrajectoryImpedanceController::updateImpedanceTarget(), AdmittanceController::updateTargetPose(), MarkerInterface::updateTargetPose(), PoseTopicInterface::updateTargetPose(), CartTrajectoryController::updateTargetPose(), ImpedanceController::updateTargetPose(), and JointTrajectoryController::updateTargetPose().
fromMsg() [4/5]
Eigen::VectorXd tf2::fromMsg (geometry_msgs::msg::Wrench raw_wrench) inline
Definition at line 25 of file Wrench.h.
References fromMsg().
fromMsg() [5/5]
Eigen::VectorXd tf2::fromMsg (geometry_msgs::msg::Wrench raw_wrench, Eigen::VectorXd & vector) inline
Definition at line 14 of file Wrench.h.
toMsg()
geometry_msgs::msg::Wrench tf2::toMsg (Eigen::VectorXd vector, geometry_msgs::msg::Wrench & wrench) inline
Definition at line 30 of file Wrench.h.
Referenced by CartTrajectoryController::cbCartTrajectory(), JointTrajectoryController::cbJointTrajectory(), MarkerInterface::configMarker(), OmegaInterface::feedback(), FTFilter::filter_cb(), nav_msgs_utility::Odometry::fromVector_3dof(), nav_msgs_utility::Odometry::fromVector_6dof(), MyIK::MyIK::getManipulabilityMarker(), rotation_util::getQuaternionErrorYaw(), CartTrajectoryImpedanceController::getTrajectories(), MarkerInterface::initInterface(), MarkerInterface::markerThread(), CartController::publishState(), MarkerInterface::resetInterface(), TwistTopicInterface::setPoseFromTwistMsg(), and geometry_msgs_utility::transformFT().