OpenHRC: MyIK Namespace Reference
MyIK Namespace Reference
Classes
class MyIK
Enumerations
enum SolveType { Pure }
enum BasicJointType { RotJoint , TransJoint , Continuous }
Functions
VectorXd getCartError (const Affine3d &T, const Affine3d &T_d)
VectorXd getCartError (const KDL::Frame &frame, const KDL::Frame &frame_d)
Enumeration Type Documentation
BasicJointType
enum MyIK::BasicJointType
Enumerator
RotJoint
TransJoint
Continuous
Definition at line 28 of file my_ik.hpp.
SolveType
enum MyIK::SolveType
Enumerator
Pure
Definition at line 27 of file my_ik.hpp.
Function Documentation
getCartError() [1/2]
VectorXd MyIK::getCartError (const Affine3d & T, const Affine3d & T_d) inline
Definition at line 238 of file my_ik.hpp.
References rotation_util::getRotationMatrixError().
Referenced by MyIK::MyIK::CartToJnt(), MyIK::MyIK::CartToJntVel_pinv(), MyIK::MyIK::CartToJntVel_qp_manipOpt(), getCartError(), HybridFeedbackController::updateTargetPose(), PositionFeedbackController::updateTargetPose(), and CartTrajectoryController::updateTargetPose().
getCartError() [2/2]
VectorXd MyIK::getCartError (const KDL::Frame & frame, const KDL::Frame & frame_d) inline
Definition at line 249 of file my_ik.hpp.
References getCartError().